- africanlii/templates/africanlii/layouts/document_detail.html
- africanlii/views/generic_document.py
- africanlii/views/generic_views.py
- africanlii/views/judgment.py
- africanlii/views/legal_instrument.py
- africanlii/views/legislation.py
This PR adds support for multiple document versions based on date and language.
* **Multiple language versions for the same date:**
* **Multiple date versions for the same language:**
* **Document without other date or language versions:**
closes #128 
closes #129
> Multiple Document Versions Support

- .gitignore
- africanlii/settings.py
- africanlii/templates/peachjam/layouts/main.html
- lawlibrary/settings.py
- lawlibrary/templates/peachjam/layouts/main.html
- liiweb/settings.py
- liiweb/templates/peachjam/layouts/main.html
- peachjam/context_processors.py
- peachjam/settings.py
- peachjam/templates/peachjam/layouts/main.html
During deploy, `python manage.py compilescss` scans all through all django templates for `scss` link references and finds the corresponding `scss file` in static to compile. The problem is that it is not intelligent enough to decipher what we had. (Not able to decipher `APP_STYLES`)
```
<link rel="stylesheet" href="{% sass_src APP_STYLES  %}" type="text/css">
```
Hence deploys are blocked
**Solution:**
We have to put an actual value. I took the alternative approach to solve this problem which was extending `main.html` and override `block head-css` in each sub app of `peachjam` (`liiweb, africanlii, lawlibrary`)
resolves https://github.com/laws-africa/peachjam/issues/283
> Fix compiling scss error which is block deploys

- peachjam/adapters/adapters.py
- peachjam/resources.py
- The issue here was that the frbr uris coming from indigo and the ones that we are generating on peachjam do not match.
- The adapter tries to create a new document from the frbr_uri provided by indigo since it can't find a match on peachjam
- This results in db integrity errors when performing the update from the ingestor.
- By reusing the frbr_uri generation methods on the core document model, we can now get the correct value and perform the update.
> Ingestor update fix

- peachjam/pipelines.py
- peachjam/static/stylesheets/components/_document-content.scss
- peachjam/templates/peachjam/_document_content.html
- requirements.txt
Also reset line-height to normal for the document text. Otherwise it uses bootstrap's adjusted line height.
Before:
After:
> When importing word, strip font and line-height

- peachjam_search/documents.py
- peachjam_search/serializers.py
- peachjam_search/views.py
* create a simple compound filter backend that will correctly join the field-based search with the nested page query search into a single "should" statement
* don't return large source fields which are not shown in the search results (and remove from serializer)
* boost title field
* use SimpleQueryString search which handles quoted searches for us
Produces a search like this:
```
"query": {
"bool": {
"should": [
{
"simple_query_string": {
"fields": [
"title^2",
"author",
"citation",
"judges",
"content"
],
"query": "africa"
}
},
{
"nested": {
"inner_hits": {
"_source": [
"pages.page_num"
],
"highlight": {
"fields": {
"pages.body": {}
},
"fragment_size": 80,
"number_of_fragments": 2,
"post_tags": [
"</mark>"
],
"pre_tags": [
"<mark>"
]
}
},
"path": "pages",
"query": {
"bool": {
"must": [
{ …
```
> Make page-based searching work

- peachjam/models/core_document_model.py
- Fixes the bug that throws 500 error when a document is saved with duplicate expression frbr uri in the model admin.
closes #330
closes #332
> Duplicate frbr uri validation

- peachjam/templates/peachjam/layouts/document_detail.html
These were lost during a merge conflict
I've moved the `json_script` blocks to the end so that they don't get in the way of substantial layout changes.
I highly  recommend viewing this diff with GitHub's "hide whitespace" turned onn
> Restore container-fluid and container layouts in document detail view

- peachjam/static/stylesheets/components/_timeline.scss
- peachjam/templates/peachjam/_timeline_events.html
- peachjam/templates/peachjam/layouts/document_detail.html
* remove cards surrounding the document metadata and document history; this makes the views a bit simpler without having to put everything in a box (it's a slippery slope otherwise)
* put an HR between the metadata and the content
* fix incorrect links in the timeline view
* increase spacing between timeline cards so that they're visually grouped
* make timeline arrows stand out more, align arrow with center of circle
* push top of timeline "line" to fall inside first circle
> Remove cards from document detail view

- peachjam/templates/peachjam/layouts/document_detail.html
- peachjam/views/generic_views.py
Version and language dropdowns show all versions, including the current one, and mark the current one as active. This makes it easier (for older dates in particular) to see which one the current one is.
> Show all versions, highlight current one

- peachjam/adapters/adapters.py
- peachjam/admin.py
Also avoid potential conflict when checking for existing related works.
> Correctly set parent work when importing

- lawlibrary/templates/lawlibrary/judgment_list.html
- removes the pagination for recent judgments
- fixes a small typo.
> Remove Lawlib pagination on recent judgments

- peachjam/js/components/FindDocuments/index.vue
- peachjam/models/core_document_model.py
- peachjam_search/apps.py
- peachjam_search/documents.py
- peachjam_search/serializers.py
- peachjam_search/signals.py
- peachjam_search/views.py
Ref #403
This allows us to only search for the most recent document when the are multiple documents for a work, at different dates. This means we'll show only the most recent piece of legislation in a search result, and not older documents.
We do this by calculating and storing (only in ES) a new field -- `is_most_recent`. A document is the most recent if it has the latest date of all documents linked to the same work. Note that there can be multiple most-recent documents, since there may be documents at the latest date in different languages.
In order to keep this field up-to-date, we need to detect when an old most-recent-document is now out of date. A signal handler checks when a document has been saved -- if it's the current most recent, it assumes that all the previous documents of …
> Store concept of most recent doc, and keep up to date

- peachjam/admin.py
- Adds date widget
The django select widget has dropdowns that show year, date and day in separate inputs. That may be more useful and faster for the editors than the calendar.
closes #439
> Date Widget

- peachjam/pipelines.py
Fixes #456 
Disallow any "position" attribute in imported docx HTML since it could move content anywhere on the page.
Before:
After:
> Strip "position: *" when importing docx

- peachjam/adapters/adapters.py
There are about 86 lawlibrary imports that are failing because of this.
> Guard against a document existing but as the wrong document type

- peachjam/admin.py
Adds the `enabled` field to the admin page. #444 did not include the necessary changes.
> Show enabled field in admin for Ingestor

- peachjam/static/stylesheets/_global.scss
Bootstrap has a class called `.alert-link` which is used for links inside `.alert`so apply that styling of `.anchor-link` to change child anchor elements of `.alert`
DEMO:
resolves https://github.com/laws-africa/peachjam/issues/321
> Match  anchor color to their type respective type of alert

- peachjam/apps.py
- peachjam/settings.py
- peachjam/signals.py
- peachjam/tasks.py
This PR configures Sentry APM for background tasks and drops the previous Elastic APM configuration.
closes #482
> Sentry APM for Background Tasks

- peachjam/models/generic_document.py
- peachjam/views/authors.py
- peachjam_search/documents.py
- peachjam_search/serializers.py
This does:
* because we now use the polymorphic object managers, we don't need to jump through hoops with elasticsearch and can just rely on inheritance
* when accessing fields specific to CoreDocument subtypes, we can rely on the fact that ES will ignore missing attributes and just return None
* use overrides to change the "doc_type" label for GenericDocument to "Document" rather than "GenericDocument"
* correctly return `author` in the serializer, not `authoring_body`
> Use polymorphic documents for elasticsearch

- lawlibrary/templates/peachjam/layouts/document_detail.html
- peachjam/static/stylesheets/components/_document-content.scss
- peachjam/templates/peachjam/judgment_detail.html
- peachjam/templates/peachjam/legislation_detail.html
https://www.loom.com/share/2989392353fe4d5b9c21699b8ea7a774
- Increased width of dt slightly so Media citation title text would not wrap
- removed uneccesary col on `dt` and `dd` elements
- Added mobile styling to decrease `dt` column slightly
Used a fixed width value that makes the key value space look close enough
resolves https://github.com/laws-africa/peachjam/issues/486
> Metadata block refactor

- lawlibrary/templates/peachjam/_footer.html
- peachjam/templates/peachjam/_footer.html
The newsletter embed that mailchimp produces, uses id as targets for its js dom functionality. Long short, if we're embed as the implementation then we cant have two duplicate forms on the same page.
So I propose adding the newsletter form at bottom of every page just before the footer
https://www.loom.com/share/afddef1e63b247f993eacd8abb247683
let me know what you think about this.
resolves #421
> Newsletter form

- peachjam/templates/404.html
- peachjam/templates/500.html
If these special templates are too complex, we run the risk of them failing when they're needed, particularly the 500.html
> Hard-code search path

- peachjam/js/components/FindDocuments/SearchResult.vue
- peachjam_search/documents.py
- peachjam_search/views.py
1. Docs without citations are being penalised, so index the title as the citation in that case, and only show the citation if it's different to the title
2. Boost title and citation scoring
Fixes #596
Requires re-indexing once merged.
Before:
After:
Before:
After:
> Improve search accuracy

- peachjam/resources.py
- This slugifies filenames before saving. 
This is because of this error
[https://sentry.io/organizations/lawsafrica/issues/3709867453/events/1d1b57e1cde345979699a1be02e43d95/](https://sentry.io/organizations/lawsafrica/issues/3709867453/events/1d1b57e1cde345979699a1be02e43d95/)
that occurs when filenames have a colon in them.
> Slugify filenames 

- peachjam_search/views.py
* improve normal `search=foo+bar` support to use `AND`  for multiple terms
* support per-field searching with `search__<field>=foo+bar` (eg. `search__title`)
* support combining general `search` parameter with  multiple per-field `search__<field>` parameters
eg: `http://localhost:8000/search/api/documents/?is_most_recent=true&search__title=child+-Rights&search=children`
```js
{
"_source": {
"excludes": [
"pages",
"content",
"flynote",
"headnote_holding"
]
},
"from": 0,
"query": {
"bool": {
"filter": [
{
"terms": {
"is_most_recent": [
"true"
]
}
}
],
"minimum_should_match": 1,
"must": [
{
"simple_query_string": {
"default_operator": "AND",
"fields": [
"title^6"
],
"query": "child -Rights"
}
}
],
"should": [
{
"simple_query_string": {
"default_operator": "AND",
"fields": [
"title^6", …
```
> Multi-field search to support advanced search

- peachjam/settings.py
I did this directly on the index via kibana, and some local testing shows this will do it always.
```
$ python manage.py search_index --delete
Are you sure you want to delete the 'peachjam' indexes? [y/N]: y
Deleting index 'peachjam'
(peachjam)➜  ~/coding/laws.africa/peachjam search-index-settings*
$ python manage.py search_index --create
Creating index 'peachjam'
$ http localhost:9200/peachjam/_settings
HTTP/1.1 200 OK
X-elastic-product: Elasticsearch
content-encoding: gzip
content-length: 248
content-type: application/json; charset=UTF-8
{
"peachjam": {
"settings": {
"index": {
"creation_date": "1667564395397",
"mapping": {
"nested_objects": {
"limit": "50000"
}
},
"number_of_replicas": "1",
"number_of_shards": "1",
"provided_name": "peachjam",
"routing": {
"allocation": {
"include": { …
```
> bump number of pages ES will index.

- lawlibrary/views/legislation.py
This PR fixes the following [Lawlibrary-17 on Sentry](https://sentry.io/share/issue/2def65f97bb74eaaaeba432f11c967af/).
* **Before:**
* **After:**
> Polymorphic N+1 Fix

- lawlibrary/templates/lawlibrary/judgment_list.html
- lawlibrary/views/judgment.py
This PR fixes [Lawlibrary-11 on Sentry](https://sentry.io/share/issue/79c82b1a552f4e018456977887b929d9/). 
Cause:
- When populating the court class dict, an additional query was made to fetch all courts for that court class
* **Before:**
* **After:**
> Judgments Page N+1 Fix

- peachjam/pipelines.py
- pyproject.toml
This PR updates the pipelines to use `cssutils` to parse styles during cleanup
closes #674
> Parse Style Fix

- peachjam/templates/peachjam/layouts/main.html
The intention here is to only report js sentry errors js files in the domain's `static/js`
Hypothetical demo:
https://www.loom.com/share/2b522b47f61c409294610ddce1b72fac
resolves #623
> On report errors from whitelist urls in sentry

- peachjam/views/courts.py
This PR aims to optimise the N+1 issue in LawLibrary at `/judgments/{code}/`
Before:
After:
Closes https://github.com/laws-africa/peachjam/issues/685
> Optimize judgments query

- peachjam/static/stylesheets/_global.scss
- peachjam/templates/peachjam/layouts/document_list.html
- peachjam/templates/peachjam/layouts/main.html
This PR adds support for disabling elements when Peachjam is running on Pocketlaw.
* **Chrome user agent:**
* **Pocketlaw user agent:**
ref #668
> Tweaks for Pocketlaw

- peachjam/adapters/adapters.py
- peachjam/views/legislation.py
This PR aims to update the code to use `work_amendments` rather than `amendments` from the metadata json.
> Amendments update

- peachjam/static/stylesheets/components/_document-content.scss
Wide screen photo:
resolves # https://github.com/laws-africa/peachjam/issues/643
> Add max width to content-and-enrichments__inner

- peachjam/views/legislation.py
This PR aims to show the correct "published in" URL by building it beforehand.
NB: See the link at the bottom left corner
The example links to [https://commons.laws.africa/akn/za/act/genn/2022/806/media/publication/za-act-genn-2022-806-publication-document.pdf](https://commons.laws.africa/akn/za/act/genn/2022/806/media/publication/za-act-genn-2022-806-publication-document.pdf) with the relevant resource.
> Build publication URL manually so as to show correct URL

- peachjam/static/stylesheets/_global.scss
- peachjam/templates/peachjam/layouts/document_detail.html
Added social media sharing links to a document for twitter and facebook. Partially tackles https://github.com/laws-africa/peachjam/issues/609
Screenshots:
Twitter share
Facebook share
> Social media share for twitter and facebook

- peachjam/templates/peachjam/article_detail.html
- peachjam/templates/peachjam/layouts/document_detail.html
- Correct class to justify-content-md-between in document detail page: (Im an idiot, I got the class name wrong)
Desktop:
Mobile:
- Correct spacing between content and breadcrumbs in article page
> Tweaks on pages

- peachjam/models/core_document_model.py
- peachjam/signals.py
- peachjam/tests/test_preferred_language.py
Previously we weren't handling deleted documents.
> Keep work languages up to date; add tests

- peachjam/settings.py
Otherwise request ids aren't fetched from nginx
> Add request id logging to middleware

- peachjam/templates/peachjam/_footer.html
- peachjam/templates/peachjam/pocket_law_resources.html
- peachjam/urls.py
- peachjam/views/__init__.py
- peachjam/views/pocketlaw.py
This PR aims to resolve static files links to show correctly on Pocketlaw.
Previously, PDFs on Pocketlaw, while offline, would not load due to how Django handles static files by adding hash values to the names, e.g. `https://lawlibrary.org.za/static/lib/pdfjs/pdf.worker.js` becomes `https://lawlibrary.org.za/static/lib/pdfjs/pdf.4a2a1c0fb5fb.js` and the worker.js is not available in the archive produced by Wget.
> Show static files links on Pocketlaw

- peachjam_search/apps.py
- peachjam_search/documents.py
- peachjam_search/views.py
* configure language-based search indexes that use language-specific analyzers to index text fields
* configure the search view to search all indexes
* documents not in one of the supported languages are indexed into the old language-agnostic index using the default "standard" analyzer.
Index mappings:
> Multi-language search indexes

- peachjam/adapters/adapters.py
This means that https://edit.laws.africa/works/akn/za/act/rules/2016/national-assembly/ is treated as a legal instrument, not legislation.
> Treat recommendation as a legal instrument, not legis

- ulii/templates/peachjam/_header.html
This PR adds gazettes to the ULII site navigation.
> Add gazettes to ulii site navigation

- peachjam/context_processors.py
- Deploy is failing because we are referencing the pj_settings in the context processor when the subleg_column is not present
> disables settings in context for deploy

- peachjam/resources.py
otherwise required column validation fails
> better row clearing for skipped

- peachjam/views/legislation.py
Before:
After:
Closes https://github.com/laws-africa/peachjam/issues/845
> Optimize query for legislation

- lawlibrary/static/stylesheets/lawlibrary.scss
- lawlibrary/templates/lawlibrary/_early_preview_warning.html
- lawlibrary/templates/peachjam/_footer.html
- lawlibrary/templates/peachjam/about.html
We have settled on "LawLibrary" as the brand name, not "Lawlibrary".
> Update lawlibrary banner; Lawlibrary -> LawLibrary

- lawlibrary/templates/peachjam/_header.html
This PR changes "SGBV Library" in the top-level navbar into "Collections" on LawLibrary.
Before:
After:
> Taxonomy tweaks

- lawlibrary/templates/lawlibrary/provincial_legislation_list.html
- lawlibrary/urls.py
- Adds a subsidiary legislation tab to the provincial legislation listing
closes #847
> Subsidiary legislation in provincial legislation listing

- .pre-commit-config.yaml
- Dockerfile
- bin/pdfjs-to-text
- package.json
- peachjam/tests/test_helpers.py
without this, we can't run pdfjs-to-text on node
> re-declare pdfjs as a node dependency

- lawlibrary/templates/peachjam/gazette_detail.html
Makes this link locality-aware:
> Gazette detail page provincial gazettes by year fix

- peachjam/templates/peachjam/_document_content.html
- peachjam/templates/peachjam/layouts/document_detail.html
This saves multiple calls to S3, and is why we store the file size locally.
> Use stored file size rather than getting size from storage

- lawlibrary/templates/lawlibrary/provincial_legislation_list.html
Otherwise we don't get the full functionality required for pocketlaw.
With javascript disabled (required for pocketlaw):
Before:
After:
> provincial legislation template must use normal legislation template

- peachjam/static/stylesheets/components/_index.scss
This PR fixes the wonky display of the years on the judgments and gazette listing pages.
To test locally:
- Delete staticfiles folder: `rm -rf staticfiles`
- Compile sass: `python manage.py compilescss`
Before:
`/judgments/court_code`
`/gazettes/code/year/`
After:
`/judgments/court_code`
`/gazettes/code/year/`
> Fix year nav

- peachjam/models/core_document_model.py
otherwise insertion into the DB fails
Fixes https://lawsafrica.sentry.io/issues/3946489610/ in sentry
> replace nulls with spaces

- peachjam/admin.py
- peachjam/forms.py
- peachjam/models/core_document_model.py
Otherwise, we download large files unnecessarily.
When the admin area is used to change the files, clear out the size and mimetype so that they get updated when the file is saved.
> Only updated attached file details when necessary

- peachjam/forms.py
- This one was a little tricky to reproduce.
- This seems to be a problem with how Django is handling pagination and ordering. The SQL works by setting limits and offsets depending on the pagination size. For some reason, some items get lost if they have similar dates and fall across the offset boundary.
- By adding another ordering clause for `title` this problem seems to go away. 
- I still don't fully understand the cause for this, but this fix seems to work, at least locally.
Loom: [https://www.loom.com/share/bcadd61bc8904cacba55842095f9c7c6](https://www.loom.com/share/bcadd61bc8904cacba55842095f9c7c6)
fixes #929
> Fix:Pagination bug skipping items

- peachjam/templates/peachjam/_document_content.html
Otherwise the per-country formatting isn't applied.
Before:
After:
> correct la-akoma-ntoso attribute

- peachjam_search/views.py
We need to re-build the search index with updated mappings to allow faceting on registry, because it must be created in the mapping as a keyword field.
Without this, search results for most queries are coming back empty or very limited.
To easily re-index all documents, we need to delete and re-creating the mapping, and then run background tasks to re-index for search. That's easiest once https://github.com/laws-africa/peachjam/pull/975 is merged.
> Faceting on registries is breaking search

- peachjam/admin.py
Fixes #978 
- We hide the source file tab if when adding a new document because user can use the upload document button.
> Hide source file tab on new document

- peachjam/js/components/DocumentContent/index.ts
- peachjam/js/peachjam.ts
- peachjam/models/core_document_model.py
- peachjam/templates/peachjam/document_popup.html
- peachjam/urls.py
- peachjam/views/__init__.py
- peachjam/views/documents.py
- peachjam/views/widgets.py
Add wikipedia-style popups for citations in document body, using the `la-decorate-external-refs` widget from law-widgets.
1. for Akoma Ntoso, this works out the box
2. for PDF and HTML, we need to first add some attributes to the `<a>` tags so that the law-widgets picks them up
https://www.loom.com/share/021f935d5f6e4080b5a44d52aee3fc70
> citation popups

- peachjam/middleware.py
- peachjam/settings.py
eg. www.lawlibrary.org.za redirects to lawlibrary.org.za, so that we don't have duplicate websites.
> Redirect www to non-www

- peachjam/resources.py
- The generic document bulk importer fails when you skip a row . 
- This adds a check for the work_frbr_uri before parsing the value.
- It also adds a validator to make sure the value exists.
closes #1094
> Fix frbr uri parse in bulk import

- peachjam/middleware.py
- tanzlii/settings.py
- zanzibarlii/settings.py
This PR adds a custom middleware that forces the default site language to be used, unless another one is set via sessions or cookies.
This has been applied for ZanzibarLII and TanzLII.
Resolves #1086
> Force default language for ZanzibarLII and TanzLII

- peachjam/js/components/FindDocuments/AdvancedSearch.vue
- peachjam/js/components/FindDocuments/AdvancedSearchFields.vue
- peachjam/js/components/FindDocuments/index.vue
* don't push all the advanced field values into each field component, only push the appropriate value
* setup and manage advanced field search data at the top level, rather than some in `index.vue` and others in `AdvancedSearch.vue`
* save and load state for the advanced field `q` values
Tip: make use of whitespace in your code. It really helps to make it readable and understandable. Separate methods with a blank line. Separate logical groups of lines with blank lines.
Tip: In general, `for (x of y) { ... }` is less wordy, easier to read, and faster than `y.forEach(x => {... })`
> Advanced search tweaks

- Dockerfile
- Procfile
* use gthread not gevent
* reduce workers to 2 and use 8 threads in each worker
* this will mean that long-running requests (eg. PDF conversion) don't block other requests
See:
* https://dev.to/lsena/gunicorn-worker-types-how-to-choose-the-right-one-4n2c 
* https://luis-sena.medium.com/gunicorn-vs-python-gil-221e673d692
> Use gthread not gevent

- peachjam/graph/ranker.py
- the ranker keeps timing out when doing the bulk update. This increases the time to 30 minutes which is hopefully enough time to update the index.
> Increase ranker bulk update timeout

- africanlii/views/agp.py
- peachjam/views/authors.py
- peachjam/views/generic_views.py
- peachjam/views/place.py
Otherwise we don't get the document language filtering behaviour
Before:
> Ensure super().get_base_queryset is used

- peachjam/admin.py
- Fixes adding generic documents. 
- The error is thrown when the parse_date function returns None and we try to pull the date from it anyway.
fixes #1112
> Fix for adding generic documents without proper dates

- peachjam/context_processors.py
- peachjam/js/components/DocDiffs/index.ts
- peachjam/js/peachjam.ts
- peachjam/js/utils/function.ts
- peachjam/templates/peachjam/layouts/main.html
* Fixes https://github.com/laws-africa/peachjam/issues/1199
* Fixes https://github.com/laws-africa/peachjam/issues/1201
* guard against fully-anonymous errors, which don't come from our code
* init sentry is typescript so we can configure it more easily
> when loading changed provisions, ignore 404s

- peachjam/tests/test_resolver.py
- peachjam/views/documents.py
- seylii/settings.py
* old seylii judgments use `court-appeal` not `court-of-appeal`: eg https://old2.seylii.org/sc/judgment/court-appeal/2023/8
* remove `new.` for sites that have been migrated
> fix redirects

- peachjam/resources.py
We are seeing repeat attempts, but the current logging doesn't make sense, so I'm adding more.
We're seeing logs like this, which seems to imply it never succeeds??
```
2023-05-15 12:30:23 INFO resources 3c49b374e2b45ba2b9404302a7270b1d 9 140690579257088 Importing row: OrderedDict([('skip', ''), ('jurisdiction', 'SZ'), ('language', 'eng'), ('case_name', 'Hlatshwayo v Lukhele'), ('case_string_override', 'Civil Case 4551 of 2007'), ('matter_type', 'Civil Case'), ('case_number_numeric', '4551'), ('case_number_year', '2007'), ('court', 'SZHC'), ('source_url', 'https://media.eswatinilii.org/files/judgments/szhc/2008/22/2008-szhc-22.rtf'), ('headnote_holding', ''), ('serial_number_override', '22'), ('judges', ''), ('date', '2008-03-07'), ('created_by', 4)])
2023-05-15 12:30:49 INFO resources …
```
> additional logging

- peachjam/adapters/adapters.py
- peachjam/adapters/gazettes.py
This fixes an issue when there are gazettes in a locality. The deleted queryset was previously not limiting the locality to `None` when looking for gazettes to delete, and so gazettes in localities were being deleted incorrectly.
This also changes the Indigo adapter to specify `resolver=none` when fetching HTML. This means that links to legislation will use the local link and not go through `resolver.laws.africa` which is unecessary. This will fix extracted citations for HTML legislation, which were currently not working. eg https://lawlibrary.org.za/akn/za/act/2021/2/eng@2021-06-04 cites the Constitution but that's not included in the "Citations" tab.
The second fix will require all legislation on all LIIs to be updated.
> Fix for gazettes adapter to not delete gazettes unnecessarily

- peachjam/models/core_document_model.py
otherwise we extract links in the generated coverpage, which makes it look like an act links to its amendments which is incorrect
> only extract data-href citations from akn html

- peachjam/templates/peachjam/_document_content.html
- peachjam/templates/peachjam/layouts/document_detail.html
* specify lang attribute on document content 
* include hreflang for alternate language links (standard requires a full URL) (a tags)
* include `<link rel="alternate"` tags for language versions
Closes #1159
> specify lang attribute on document content 

- tanzlii/templates/peachjam/_header.html
- zanzibarlii/templates/peachjam/_header.html
- adds licensed advocates menu item
- removes speeches and document guidelines menu items
closes #1158
> Zanzibarlii menu items

- peachjam/resources.py
We were previously using the value in the authors column as the name of the author, instead of using it as the code. The resultant effect is that we're creating authors, instead of filtering them and then updating their document.
> Bug fix for author import field

- peachjam/admin.py
This happens when the import spreadsheet has "invalid dimensions" meaning invalid columns
> Fixes index error in import

- peachjam/js/peachjam.ts
This should reduce error spam where the error doesn't come from inside our code.
> ignore js errors without a stack trace

- .github/workflows/deploy.yml
- eswatinilii/templates/peachjam/_footer.html
- ghalii/templates/peachjam/_footer.html
- lawlibrary/templates/peachjam/_footer.html
- lesotholii/templates/peachjam/_footer.html
- liiweb/templates/peachjam/_footer.html
- malawilii/templates/peachjam/_footer.html
- namiblii/templates/peachjam/_footer.html
- peachjam/settings.py
- peachjam/tests/test_resolver.py
- peachjam/views/documents.py
- seylii/templates/peachjam/_footer.html
- sierralii/templates/peachjam/_footer.html
- tanzlii/templates/peachjam/_footer.html
- tcilii/templates/peachjam/_footer.html
- ulii/templates/peachjam/_footer.html
- zambialii/templates/peachjam/_footer.html
- zanzibarlii/templates/peachjam/_footer.html
- zimlii/templates/peachjam/_footer.html
* also reduce sentry tracing sample rate to 25% of queries, we're going through our free tier too quickly
> redirect new.foo to foo; agp.africanlii.org to africanlii.org

- peachjam/helpers.py
- peachjam/templates/peachjam/_registries.html
- peachjam/views/courts.py
- peachjam/views/gazette.py
This PR:
- Fixes the court registry listing on the court detail and court registry detail pages.
- Adds a `chunks` helper method that splits a list into n-sized chunks.
https://www.loom.com/share/803b90b4377f48ca93f1d81b114b4c69?sid=4a8c2776-8816-4612-8c00-52f1f08fb75a
> Fix court registries list

- africanlii/settings.py
- peachjam/settings.py
- peachjam_search/documents.py
- peachjam_search/views.py
Otherwise gazettes.africa doesn't show it correctly. Corresponding fix for Gazettes.Africa to follow shortly.
> Better control of when to show jurisdiction filter

- peachjam/static/stylesheets/_global.scss
Otherwise, iphone zooms into the input box, which is a weird experience.
We wouldn't have this issue if our base font size was 1rem (usually 16px), but we reduce it because otherwise the site's font size is too large.
See https://makersaid.com/disable-safari-auto-zoom-on-form/
> Force input boxes on mobile to use 16px fonts

- peachjam/models/core_document_model.py
This fixes some validation errors in new form.
- When clicking on save without editing the form
- When adding a duplicate document. 
fixes #1329
fixes #1330
fixes #1331
> Fix validation errors in new forms

- peachjam/resources.py
- peachjam_search/documents.py
- peachjam_search/views.py
* use minimum_should_match (see https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html and https://github.com/laws-africa/peachjam/issues/1161)
* index `case_name` for citator searches
* import/export allows created_at
> Search improvements

- africanlii/settings.py
- eSwatiniLII was missing from agp indexes.
> Add eSwatiniLII to agp index list

- peachjam_search/documents.py
- peachjam_search/tests.py
* define prepare_... methods dynamically
* prepare method checks for existing of attribute before calling it, because different sites may have different languages configured
> test for translated field; meta programming

- liiweb/views/general.py
- peachjam/templates/peachjam/_taxonomy_list.html
- peachjam/views/article.py
- Some of the consecutive queries come from the taxonomies. This attempts to reduce them by getting using the get_root_nodes function.
fixes #1347
>  Fix consecutive db queries

- africanlii/resources.py
- africanlii/templates/africanlii/_ratification_table.html
- peachjam/templates/peachjam/_ratifications.html
- Fixes the import issue where the dates were switched while importing
- Changes the display order
closes #1379
closes #1380
> Fix ratification import fields

- peachjam/pipelines.py
This fixes #1261 by allowing us to upload an OpenOffice (actually, libreoffice) document which has corrected footnote symbols.
> additional open office mime type

- peachjam/models/core_document_model.py
- Fixes a server error when a user saves a document without date but with work identification details present.
fixes #1369
> Fix datetime admin bug

- peachjam/models/core_document_model.py
- peachjam/models/generic_document.py
- peachjam_search/documents.py
- peachjam_search/views.py
This allows us to demote certain documents in search results. The penalty is simply subtracted from the score.
This will allow us to push amendment legislation lower in results than principal legislation.
Disabled until the new field is populated.
> search penalty

- peachjam/admin.py
- peachjam/templates/admin/tree_change_list.html
Replace the old taxonomy tree admin view with a tree-based view that shows the entire tree at once.
The only functionality this effectively hides is the drag-and-drop to re-order the entries.
@actlikewill here's the simplest way to integrate la-table-of-contents-controller with the taxonomy tree.
> Use la-table-of-contents-controller for taxonomy tree admin

- peachjam/settings.py
- peachjam_api/urls_public.py
* Fixes the url from `.../api/v1/v1/gazettes` to `.../api/v1/gazettes`
* ensures `get_absolute_url` knows what header to look for to know the original request was secure
> Fix API url, and ensure building absolute urls uses https

- peachjam/adapters/adapters.py
- peachjam/admin.py
- peachjam/tasks.py
- indigo adapter can fetch for multiple place codes, simplifying cases where we need to fetch content for multiple places from the same API
- ingestors run as separate background tasks so that they fail and refresh independently
This will require existing ingestor adapters to be updated:
* ensure `api_url` is `https://api.laws.africa/v2`
* remove `url`
* ensure `places` is the correct list of place codes
> Indigo adapter can handle multiple place codes; bg tasks

- lawlibrary/constants.py
- lawlibrary/context_processors.py
- lawlibrary/settings.py
- lawlibrary/templates/peachjam/_header.html
- lawlibrary/templates/peachjam/legislation_detail.html
- lawlibrary/urls.py
- lawlibrary/views/legislation.py
- liiweb/templates/liiweb/locality_legislation.html
- liiweb/templates/liiweb/locality_legislation_list.html
- liiweb/views/legislation.py
> By-laws on LawLibrary

- peachjam/models/generic_document.py
- peachjam/models/judgment.py
- peachjam_search/tasks.py
* check labels before removing or adding -- otherwise this triggers an unnecessary search index update even if nothing has changed
* when a many-to-one model changes, the `instance` to `handle_save` is the document, but `sender` is, say, a `Bench` class or a `CoreDocument_labels` class. So this change correctly uses the document model class name that is queued up to be re-indexed, not the sender.
* handle deletion of related models as a background task (eg. when a label is removed from a document)
> check labels first; correct model to re-index; re-index related

- peachjam/js/components/DocumentContent/index.ts
- peachjam/js/components/DocumentContent/pdf-renderer.ts
- peachjam/templates/peachjam/_document_content.html
- peachjam/templates/peachjam/layouts/document_detail.html
When sharing a PDF, we'll share "Title - Page 2 - URL#page-2"
When sharing a portion of an HTML document, we'll share "Title - Section 32 - URL#sec_32"
This is required for the law reader project to ensure that users can easily share the current portion/page of the document they are reading.
About 77% of shares through our share buttons are for whatsapp.
> Sharing URLs take current page portion into account

- peachjam/settings.py
This is a bit of a hack until we can turn this off completely
> rds proxy doesn't allow -c args

- peachjam/resources.py
django-import-export doesn't treat inputs like form fields in django, so we must explicitly strip whitespace from input fields
> strip whitespace

- lawlibrary/templates/liiweb/locality_legislation_list.html
- liiweb/templates/liiweb/legislation_list.html
- liiweb/templates/liiweb/locality_legislation_list.html
- liiweb/views/legislation.py
- open_by_laws/templates/open_by_laws/municipal_by_laws_list.html
- peachjam/admin.py
- peachjam/models/core_document_model.py
- peachjam/models/taxonomies.py
This enables us to have a richer experience on legislation views, similar to what we do on court and taxonomy detail views.
* lays the groundwork for #1461 to support profiles at the top-level legislation level (this only covers locality legislation)
* also fixes how we find entity profiles for taxonomy topics
* ref #1461
> locality legislation view uses entity profiles from locality

- africanlii/locale/en/LC_MESSAGES/django.po
- africanlii/locale/fr/LC_MESSAGES/django.po
- africanlii/locale/pt/LC_MESSAGES/django.po
- africanlii/locale/sw/LC_MESSAGES/django.po
- liiweb/locale/en/LC_MESSAGES/django.po
- liiweb/locale/fr/LC_MESSAGES/django.po
- liiweb/locale/pt/LC_MESSAGES/django.po
- liiweb/locale/sw/LC_MESSAGES/django.po
- peachjam/locale/en/LC_MESSAGES/django.po
- peachjam/locale/fr/LC_MESSAGES/django.po
- peachjam/locale/pt/LC_MESSAGES/django.po
- peachjam/locale/sw/LC_MESSAGES/django.po
- peachjam/views/legislation.py
- scripts/extract-translations.sh
- tanzlii/locale/en/LC_MESSAGES/django.po
- tanzlii/locale/fr/LC_MESSAGES/django.po
- tanzlii/locale/pt/LC_MESSAGES/django.po
- tanzlii/locale/sw/LC_MESSAGES/django.po
- zanzibarlii/locale/en/LC_MESSAGES/django.po
- zanzibarlii/locale/fr/LC_MESSAGES/django.po
- zanzibarlii/locale/pt/LC_MESSAGES/django.po
- zanzibarlii/locale/sw/LC_MESSAGES/django.po
* fixed warnings so that they can be correctly translated. The full string must be passed to `_()` directly, otherwise the gettext pre-processing can't find the strings to translate. The `friendly_type` must be passed in as a parameter.
* updated translation string extractions
(translations still pending):
> updated out-of-date warning

- peachjam_search/documents.py
otherwise we're checking for PDFs in multiple places
> when indexing for search, trust get_text_content

- peachjam/forms.py
- peachjam/js/components/FilterFacets/SingleFacet.vue
- peachjam/models/core_document_model.py
- peachjam/views/authors.py
- peachjam/views/courts.py
- peachjam/views/generic_views.py
- peachjam/views/taxonomy.py
This does three things:
1. allows us to fetch only the latest expression in taxonmy views, since they may include legislation, which has multiple points in time. Otherwise, the same act will show up multiple times. It's opt-in, because it's a bit more expensive, and many views (eg. court and place listing views) don't care about it.
2. fixes https://github.com/laws-africa/peachjam/issues/1522 by applying language filtering only to the queryset that is actually used for document listing. This makes faceting calculations faster because we don't care about languages when calculating facets.
3. pushes facet calculations into the db, rather than fetching all rows and then calculating facets in python
Before:
After:
> fix latest expression in taxonomy view; faster faceting.

- peachjam/js/components/FindDocuments/index.vue
The string wasn't matching correctly with the period.
The translations already have it so its fine.
> Fix doc count string

- peachjam/admin.py
- peachjam/models/judgment.py
- This was caused by the registry drop down.
- The __str__ method has self.name and self.court which causes the n+1 issue.
- Maybe a simple solution  could be to remove the court from the str method. The names of the registries that Tanzli are using are quite descriptive themselves, indicating the court itself, which may be enough
closes #1393
> Fix n+1 in judgment admin

- peachjam/templates/peachjam/layouts/document_detail.html
- fixes showing relationships as object.
closes #1572
> Related documents in metadata

- peachjam/views/legislation.py
fixes #1590
- Sometimes the metadata has "commencments: null" and which passes None to the list comprehension
- Sometimes the commencements keyword is missing altogether
- This should guard against those two cases
> Fix null in commencements metadata

- peachjam/views/generic_views.py
> Fix n+1 for document citations

- peachjam/analysis/citations.py
- peachjam/models/citations.py
- peachjam/models/core_document_model.py
- peachjam/views/documents.py
* updates to calling Citator API for text documents
* update document resolver to handle FRBR URI portions (eg. `/akn/za/act/2009/1/~sec_31` is redirected to `/akn/za/act/2009/1/#sec_31`)
> Updates to support improved text citation extraction and the new citator api

- peachjam/helpers.py
- peachjam/urls.py
fixes #1591 
The error occurs because the date captured by the urlconf was not being validated correctly.
Adding a more explicit regex that looks for the format `YYYY-MM-DD` fixes it.
> Add regex to article url

- peachjam_search/views.py
otherwise an authorised user's cache may be shared with a non-authorised user, when the server-side cache is used
> ensure that search caching varies across cookies

- peachjam_search/documents.py
- peachjam_search/views.py
previously we indexed the title as the citation. the problem is that then documents without a citation get double points for matching on the title, which skews results.
also, boost title slightly since many searches are directly on the title
> search: boost title; don't double-index title as citation

- peachjam/settings.py
- peachjam/signals.py
- peachjam/tasks.py
* `/static/...` aren't useful and take up request quota with sentry
* correctly wrap background tasks so we can check performance and get better errors
* attach `app_name` tag to all events to differentiate more easily between apps
example of background task:
> Sentry updates: ignore /static/ and correctly wrap background tasks

- peachjam/middleware.py
- peachjam/settings.py
Caches successful GET and HEAD requests for anonymous and non-staff users, for 30 minutes.
Excludes /admin, /accounts, etc.
> cache most of the site for anonymous and non-staff users

- liiweb/views/general.py
> Recent legislation list on home page is acting weirdly

- peachjam/templates/peachjam/_document_content.html
> As a user, I'm frustrated that so many PDF judgments require me to click a button before displaying

- lawlibrary/templates/peachjam/layouts/main.html
- Setup Plausible and Matomo analytics services as an alternative to Google Analytics for a trial run.
> Setup Plausible and Matomo

- peachjam/resolver.py
- peachjam/settings.py
- peachjam/templates/peachjam/document_popup.html
- peachjam/tests/test_resolver.py
- peachjam/views/documents.py
- peachjam/views/widgets.py
- pyproject.toml
The idea here is that a user can hover over an FRBR URI link on, say, africanlii.org. It will try to fetch the popup for the link on africanlii.org. If AfricanLII doesn't have the document, it'll use the resolver to determine which LII does, and send a redirect to the popup on that LII. The browser follows the redirect and CORS permits the request.
Additionally, if it's a CORS/offsite request, then the popup includes the partner site's name.
> cross-origin popups

- africanlii/settings.py
- africanlii/views/taxonomy.py
- lawlibrary/settings.py
- peachjam/context_processors.py
- peachjam/settings.py
- peachjam/templates/peachjam/_document_table.html
Closes #1646
Loom: https://www.loom.com/share/744292bf14c24d049528c369f1343583?sid=3217dbf5-1583-42f0-842c-8ec87785a200
> In listing views, I want to see locality information if applicable

- peachjam/models/core_document_model.py
- peachjam/resources.py
- This adds a method for calling the objects without defer in the fields for use in the importer
> Fix bulk importer updates

- peachjam/admin.py
- peachjam/forms.py
- peachjam/models/core_document_model.py
- This allows us to update the source file meta data when the file is changed in the admin. 
#1737
> Update source file details on file change

- peachjam/js/components/FindDocuments/AdvancedSearch.vue
- peachjam/js/components/FindDocuments/index.vue
- Closes #1766 
- I found that _disableDate_ was turning the criteria into an object, so I fixed that.
- I added a condition to check that the criteria is an array.
> TypeError: this.advancedSearchCriteria.some is not a function

- peachjam/js/utils/function.ts
> When generating a TOC for HTML documents, don't generate entries for headings without text

- peachjam/settings.py
before_send is called for errors
before_send_transaction is called for non-errors
this fixes an issue where app_name is not set on errors sent to sentry.
> decorate sentry events AND errors

- peachjam/js/components/FindDocuments/index.vue
- peachjam/js/components/analytics.ts
Since the URL params contain both keywords and facets, I figured the easiest way to track would be to use the entire params as the keyword like this:
` 
this.paq.push(['trackSiteSearch', keyword, false, searchCount]);
`
If you'd rather I destructure it instead, please let me know.
Closes #1757
> Change matomo site search tracking to use trackSiteSearch

- peachjam/admin.py
- peachjam/models/journals_books.py
when re-extracting citations from markdown docs, we don't want to lose any existing /akn citations that may already be in place.
in time, we probably want to guard against this in all document types, but having /akn refs in non-markdown (and non-AKN) docs is very rare.
This allows our law reader books to have /akn refs baked into them.
> don't lose embedded /akn citations from markdown docs

- peachjam/js/components/FindDocuments/index.vue
- peachjam/models/judgment.py
- peachjam/templates/peachjam/_registries.html
- peachjam/templates/peachjam/judgment_detail.html
- peachjam/tests/test_admin.py
- peachjam/views/courts.py
- peachjam_search/views.py
- This adds model label for court registry
> Model label for court registry

- peachjam/templates/peachjam/judgment_list.html
This adds quick search to the judgment listing page
closes #laws-africa/kenyalaw-pj#30
> Quick search in judgment listing page

- peachjam_search/serializers.py
- peachjam_search/views.py
for some searches, particularly advanced searches, the match is on the .exact field. If we don't highlight that field, we don't get highlights. To make the client's work easier, we merge highlights from pages.body.exact into pages.body (for example), if a highlight doesn't already exist.
> merge highlights for provisions/pages .exact field with main field

- peachjam/admin.py
- peachjam/models/citations.py
- peachjam/models/core_document_model.py
- peachjam/tasks.py
* run re-extract citation tasks on a saturday at a random hour
* associated document background tasks with their document
* show background tasks in the document admin for easier debugging
* run some tasks at a lower priority
> re-extract citations on weekends, show background tasks

- peachjam/views/books.py
- tanzlii/templates/peachjam/_header.html
- Add causelist to tanzlii header
> Causelists in tanzlii header

- peachjam/admin.py
- peachjam/views/autocomplete.py
* subject/object should be reversed
* also makes work autocomplete a bit broader
@NotoriousMBB I owe you a croissant
> fix direction of related judgments in admin view

- lawlibrary/views/legislation.py
- liiweb/templates/liiweb/legislation_list.html
- liiweb/views/legislation.py
- open_by_laws/views/by_laws.py
- peachjam/js/components/LegislationTable/TableRow.vue
- peachjam/js/components/LegislationTable/index.vue
- peachjam/static/stylesheets/components/_index.scss
- peachjam/static/stylesheets/components/_tables.scss
- peachjam/templates/peachjam/_document_table.html
- peachjam/templates/peachjam/_grouped_judgments_table.html
- peachjam/templates/peachjam/_judgment_table.html
- peachjam/views/legislation.py
- peachjam_api/serializers.py
* replace tables with responsive document tables that collapse on mobile
* legislation listing uses FRBR year, rather than date, and always has this column
* legislation listing shows group headings based on sort key
* legislation listing includes labels
* document tables make better use of whitespace, particularly on mobile, to show more data with less padding
* legislation table now looks the same as the other document tables
https://www.loom.com/share/aae4f89d15b74fe5b1bbc1756f545952
> Responsible document table and improved legislation listing

- liiweb/templates/liiweb/legislation_list.html
- liiweb/urls.py
- liiweb/views/legislation.py
This adds the recent legislation tab.
closes #1832
> Recent legislation tab

- peachjam/templates/peachjam/legislation_detail.html
set empty default in citation sub title
> Check for none in citaiton

- peachjam_search/views.py
This was fixed weeks ago but not merged and pushed.
> ignore nulls when saving searches

- peachjam_search/views.py
> don't allow queries for both normal and advanced search to be combined

- africanlii/templates/africanlii/au_institution_detail.html
- africanlii/templates/africanlii/au_organ_detail.html
- africanlii/templates/africanlii/member_state_detail.html
- africanlii/templates/africanlii/regional_economic_community_detail.html
- africanlii/templates/peachjam/reports_guides_list.html
- africanlii/views/au.py
- liiweb/views/legislation.py
- peachjam/forms.py
- peachjam/settings.py
- peachjam/static/stylesheets/components/_loaders.scss
- peachjam/templates/peachjam/_count_and_search.html
- peachjam/templates/peachjam/_document_count.html
- peachjam/templates/peachjam/_document_table.html
- peachjam/templates/peachjam/_document_table_form.html
- peachjam/templates/peachjam/_quick_search.html
- peachjam/templates/peachjam/court_detail.html
- peachjam/templates/peachjam/judgment_list.html
- peachjam/templates/peachjam/layouts/document_list.html
- peachjam/views/generic_views.py
- peachjam/views/legislation.py
* fix filtering when there are no results
* change htmx-swap so that there aren't duplicate forms
* progress bar
* move quick search to the side of document count
* re-use templates
* default sorting for document lists
https://www.loom.com/share/253a8739ba454e4295efbb4ae1f2d315
> fix filtering; don't duplicate form; progress bar

- peachjam/admin.py
This bug occurs when adding a dupilcate taxonomy from the admin. 
Adding validation via `clean` on the model doesn't work as expected, because treebeard has some extra logic in the `save` method in `MoveNodeForm`. it ends up overriding the native behaviour that catches validation errors thrown from the model. Having the logic on the form works better, with some extra work to get the appropriate parent to validate the slug.
closes #1915
> Check for duplicates in taxonomy admin

- peachjam/views/documents.py
> fix PDF downloads

- peachjam/forms.py
fixes https://lawsafrica.sentry.io/issues/5633502588/
> validate years before using them

- peachjam/views/courts.py
- peachjam/views/generic_views.py
This adds taxonomies to the court listing pages
Also some small refactors to eliminate some repitition in the facets code.
closes https://github.com/laws-africa/kenyalaw-pj/issues/132
> Add taxonomies to court listings

- peachjam/js/components/clipboard.ts
- peachjam/settings.py
- peachjam/templates/peachjam/_document_table.html
- peachjam/templates/peachjam/_quick_search.html
- peachjam/templates/peachjam/judgment_detail.html
- peachjam/templates/peachjam/layouts/document_detail.html
- peachjam/views/courts.py
- peachjam/views/generic_views.py
* document table headers can be configured; judgements use "Citation" and "Judgment date"
* advanced search links for quick search
* copy-to-clipboard includes links (ie. HTML and text)
> Small changes

- peachjam/static/stylesheets/_variables.scss
setting the primary color variable as the default value fails to compile properly. I've harcoded a default value that gets overridden in the other stylesheets
> fix default variable value for visited link

- liiweb/views/legislation.py
The children are not present on the qs when we do the variant filter on the get_base_queryset method. This moves the variant filter to the get queryset method leaving the base_queryset intact so we can fetch the children.
closes https://github.com/laws-africa/peachjam/issues/1971
> Fix sublegislation dropdown

- liiweb/views/legislation.py
This fixes sublegislation ordering, on both the drop down and the listing page
closes https://github.com/laws-africa/kenyalaw-pj/issues/201
> Fix sublegislation ordering

- peachjam/views/generic_views.py
this ensures that all images, even in AKN HTML, have the correct URL including the document's full expression FRBR URI.
Otherwise, for a document URL such as  `http://localhost:8001/akn/za/act/1996/constitution/eng@2013-08-23` the image url `media/foo.png` becomes `http://localhost:8001/akn/za/act/1996/constitution/media/foo.png` which is not correct.
> always rewrite images in document content

- pyproject.toml
testing to see if 6.0.0 is also broken
whitenose 5.3.0 fixes our db issues!
> pin whitenose 6.0.0

- peachjam/views/robots.py
fixes #2006
```
User-agent: *
Allow: /
Disallow: /search/
Disallow: /api/
Disallow: /akn/ke/judgment/kehc/2022/13019/
Disallow: /akn/ke/judgment/keelc/2022/14600/
Disallow: /akn/ke/judgment/keca/2022/989/
Disallow: /akn/ke/judgment/keelrc/2022/1728/
Disallow: /akn/ke/judgment/kehc/2018/6377/
Disallow: /akn/ke/judgment/kehc/2021/6429/
Disallow: /akn/ke/judgment/kehc/2019/1049/
Disallow: /akn/ke/judgment/kehc/2017/4559/
Disallow: /akn/ke/judgment/kehc/2022/11441/
```
> robots.txt must disallow entire work detail

- lawlibrary/urls.py
This fixes the base view that is used for the national legislation listing views.
The base view should filter out documents that have localites
closes https://github.com/laws-africa/peachjam/issues/1979
> Fix locality filters for Lawlibrary

- peachjam/admin.py
* ensure we return cleaned_data
* only try to validate the slug if everything else is fine
fixes https://lawsafrica.sentry.io/issues/5664068012/
> don't break when validating taxonomy slug

- peachjam/templates/peachjam/saved_document_update.html
- peachjam/views/save_document.py
- This fixes a bug where creating a new folder without the name resulted in the page reloading without context
- Adds the underline to the folders link in the modal.
closes https://github.com/laws-africa/peachjam/issues/2016
> Saved doc fixes

- peachjam/adapters/gazettes.py
- peachjam/models/gazette.py
- peachjam/tests/test_documents.py
now that everything has a nature, gazettes with a legitimate subtype shouldn't lose that subtype
fixes https://github.com/laws-africa/peachjam/issues/2025
> don't force a sub-type on gazettes

- peachjam/forms.py
later we must give outcomes a slug/code so that we support translations
fixes https://lawsafrica.sentry.io/issues/5804276287/
> use outcomes__name not outcomes__code

- peachjam/settings.py
the reasoning is that 99% of our requests are GETs which don't require atomic, and this is placing load on pgbouncer and psql.
> disable atomic requests

- lawlibrary/templates/liiweb/home.html
this makes it easier to jump to the primary content types on mobile, when the menu is collapsed
> add main content type buttons for mobile on lawlibrary

- peachjam/js/components/FindDocuments/index.vue
This makes it clearer what the best matching document types are
The other fields sort by alpha because they are often long and alpha makes it easier to browser through the multiple values
closes #1965
> search result sorts document type by count (desc)

- peachjam/templates/429.html
All auth has default rate limits for some views but no templates to render 
closes https://github.com/laws-africa/peachjam/issues/1989
> Add 429.html

- peachjam/views/documents.py
see https://github.com/laws-africa/peachjam/issues/2024
it doesn't fix the root cause, but it means that views will succeed for now until we fix the underlying data
> tolerate multiple attachments with the same name

- peachjam/settings.py
- peachjam/signals.py
- peachjam/templates/admin/_comments_form.html
- peachjam/templates/admin/_comments_form_combo.html
- peachjam/templates/admin/_comments_list.html
- peachjam/templates/admin/change_form.html
- peachjam/urls.py
- peachjam/views/comments.py
- pyproject.toml
This adds comments in the admin area for documents (actually, for any object that can be modified in the admin).
* use django-contrib-comments
* users must be staff to be able to make comments - a signal is used to enforce this
* use htmx to submit the form independently of the edit form that covers most of the page
* because the comment box itself, and the comment form itself, must be in separate parts of the page (because HTML doesn't allow nested forms), when the comment list is updated by htmx after a comment is made, we use hx-oob-swap to also update the form at the bottom of the page.
Fixes #1974
> Comments in admin area for documents

- peachjam/apps.py
Before this change, the daily and weekly tasks were scheduled to run "in 1 day" and "in one week", and then daily/weekly after that.
The problem is that every time we deployed an update, it re-scheduled the tasks. So the weekly task in particular just never got run, because it was continually pushed out.
Instead, we now schedule as "run on this date" and then repeat daily/weekly.
> correctly schedule regular tasks

- peachjam/models/core_document_model.py
- peachjam/models/judgment.py
- peachjam/tasks.py
This adds the convert html to pdf method to the judgment model
> Add convert html to judgment

- peachjam/static/stylesheets/components/_document-content.scss
this makes editorial remarks stand out a bit more
> background colour for remarks, except na

- peachjam/templatetags/peachjam.py
- peachjam/views/generic_views.py
This prevents a major performance issue with very large datasets (> 50,000) where crawlers can page through the entire dataset, hurting PostgreSQL because `OFFSET` pagination in psql is inefficient.
See https://readyset.io/blog/optimizing-sql-pagination-in-postgres
https://www.loom.com/share/973f54014ae94bb4b18bb2bfd5b6266e
> clamp pagination at 10 pages

- peachjam/urls.py
some models eg country in countries_plus have letters in the pk 
https://lawsafrica.sentry.io/issues/5914901445/events/0fb1e238b89f43ecb51e8b6b1bfb2d72/
> Comments url should support alphanumeric slug

- peachjam/models/citations.py
- peachjam/models/core_document_model.py
- peachjam/templates/peachjam/_citations.html
- peachjam/templates/peachjam/_citations_list.html
- peachjam/templates/peachjam/_citations_list_items.html
- peachjam/templates/peachjam/_citations_list_more_button.html
- peachjam/templates/peachjam/layouts/document_detail.html
- peachjam/urls.py
- peachjam/views/documents.py
- peachjam/views/generic_views.py
https://www.loom.com/share/5584208b940e476b9662234b5af9a8b7
This changes how we render citation lists, so that documents that are heavily cited don't have very long page load times.
* only show the first 10 of each group
* use htmx to load the next ten, etc.
Also changes to link to the cited works using the full expression FRBR URI, not the work uri.
Also reduces py-4 to py-3 since our base font size is a  bit bigger.
> Citations speed

- peachjam/adapters/indigo.py
> Check for duplicate images in adapter

- liiweb/views/legislation.py
fixes https://github.com/laws-africa/peachjam/issues/2063
the latest_expression orders by `-date`
> Filter for latest expressions for subleg

- liiweb/views/legislation.py
- peachjam/forms.py
- This adds the frbr uri number as a secondary sort parameter for subleg
- The ordering needs to be reversed if the order date sorting is reversed
closes https://github.com/laws-africa/kenyalaw-pj/issues/115
> Order subsidiary legislation by frbr_uri number 

- peachjam/js/components/FindDocuments/index.vue
For a simple search, if the search string doesn't have quotes, suggest the user wraps the search in quotes to find more exact matches. The user can click the click to do so.
Closes https://github.com/laws-africa/peachjam/issues/1963
> prompt user to try using "quotes" in search

- peachjam/adapters/indigo.py
- peachjam/templates/admin/change_form.html
This makes modals in admin area work again
also extra logging for ingestors
> bootstrap 5 must not conflict with bootstrap 4 in admin

- lawlibrary/tests/test_legislation_views.py
- lawlibrary/urls.py
- lawlibrary/views/legislation.py
- liiweb/tests/test_legislation_views.py
- liiweb/views/legislation.py
this means that a country lii can have other country's legislation (eg. for treaties from the AU or UN), but not include them in the national legislation lists.
> base legislation list view optionally shows only national legislation

- peachjam/views/causelist.py
- peachjam/views/courts.py
This caches the years for the court and causelist views. We use the base view name for the cache key which is typically the court or registry name.
Fixes https://github.com/laws-africa/peachjam/issues/2115
> Add years to cache

- africanlii/views/taxonomy.py
- peachjam/graph/ranker.py
- peachjam_search/apps.py
- peachjam_search/documents.py
- peachjam_search/management/commands/search_index.py
- peachjam_search/views.py
This enables per-language synonyms in elasticsearch. Currently only English synonyms are provided.
* setup a new search-only analyzer for text fields
* a new `search_index` mgmt command option to update the synonym details in elasticsearch.
* this has to take into account that some fields in some indexes have the `standard` analyzer set, and this can't be changed without re-index (unfortunately).
Once deployed, this is set up with `python manage.py search_index --update-indexes`
> Synonyms in search

- peachjam/forms.py
- peachjam/templates/peachjam/_court_list.html
- peachjam/templates/peachjam/_quick_search.html
- peachjam/templates/peachjam/judgment_list.html
- peachjam/tests/test_views.py
- peachjam/urls.py
- peachjam/views/courts.py
* new view for judgments from all courts
* link to all courts from top of judgments page
* short court groupings as cards -- the big win here is that the "all judgments" link can go into the card footer
* labels faceted, for exploring reported judgments
> All judgments view, labels facet

- peachjam/forms.py
- peachjam/views/courts.py
This allows us to facet on reported judgments.
> add labels facet to judgment lists

- peachjam/js/components/FindDocuments/index.vue
- peachjam/views/legislation.py
* search facet ordering updated to put most commonly used at the top
* legislation facet ordering updated to move alphabet first, since it's heavily use in KE (and more used than other facets in other places)
> Field ordering for legislation listing and search results

- peachjam/models/article.py
otherwise, this tries to lookup, for example, name_fr__iexact=...
fixes https://lawsafrica.sentry.io/issues/6035652754/
> fix lookups on tag name when language is not EN

- peachjam/templates/peachjam/_timeline_events.html
- peachjam/views/legislation.py
Currently, we use the 'raw' data for linking to a publication document in the timeline. 
In the cases where the publication document URL includes exactly `https://api.laws.africa/v3/` (when a PDF was uploaded, rather than linked to, on the platform), we point the link to `https://commons.laws.africa/` instead.
However, this assumes both that a peachjam lii always has the same API URL, and that all peachjam lii publication documents are on commons.laws.africa, and neither of these assumptions has been borne out.
We have also in the meantime added a PublicationFile model and a related view, which we use in the document detail view.
This brings the link in the timeline in line with the document detail view by using the same view to link to the publication document.
> use DocumentPublicationView from timeline too

- peachjam/adapters/indigo.py
this gives us more flexibility, and let's us say "everything in za" without including za itself. If we want both, we use `za za-*`
> ingestor should not include 'za' for the 'za-*' place code

- peachjam/settings.py
- peachjam_search/views.py
we have been having silent failures for a while. it's better to fail loudly so we can fix the issue than silently
> raise exception on shard failure

- peachjam/models/attachments.py
- peachjam/tests/test_storage.py
Previously we only did this for sites that used a CDN on top of S3. But there's no harm in doing it for S3 in general, and makes it easier to migrate from S3 to a CDN later.
> When saving a source file to S3, give it a friendly download filename.

- peachjam/models/citations.py
> iterate through docs only if available

- peachjam/models/core_document.py
- peachjam/templates/peachjam/document_popup.html
- peachjam/views/widgets.py
this potentially saves two unnecessary trips to the db, and uses the work__frbr_uri unique index
before:
after:
> optimise object lookup

- peachjam/helpers.py
- peachjam/tests/test_helpers.py
improve chunking:
* don't get empty lists
* don't get lots of small lists
* if lists are uneven lengths, the first few lists should get the extra entries
solves this uneven-ness:
> better chunking

- peachjam/templates/peachjam/_document_table_row.html
this broke when added multiple authors, we can simply show the first one on the listing page
before:
after:
> fix document author on listing page

- peachjam/templates/peachjam/_registries.html
- peachjam/views/courts.py
splitting getting registries to a method allows us to override it. to better support tribunals in KL
> add get registries method

- peachjam/js/components/DocumentContent/ShareSelectionModal.vue
- peachjam/static/stylesheets/_global.scss
- peachjam/static/stylesheets/_variables.scss
- peachjam/templates/peachjam/article_detail.html
- peachjam/templates/peachjam/layouts/document_detail.html
- Closes #2223 
- This is a draft to show how it currently works. If you'd like to change something, kindly let me know.
- There are also share buttons on the article detail page and share selection modal. Should I add it there as well?
- You can also mention other places you'd like me to add the email share to.
> added email share

- peachjam/templates/account/login.html
- peachjam/templates/admin/login.html
- peachjam/templates/peachjam/_header.html
- peachjam_search/templates/peachjam_search/_saved_search_modal.html
* redirect back to original page when logging in - django-allauth handles this correctly if ?next=xxx is passed in
* use POST so that the intermediate "you're about to login with a social provider" page is skipped
> social login improvements

- peachjam/js/components/floating-header.ts
- peachjam/js/components/index.ts
- peachjam/static/stylesheets/_variables.scss
- peachjam/static/stylesheets/components/_document-content.scss
- peachjam/templates/peachjam/_document_content_sidebar.html
- peachjam/templates/peachjam/_document_detail_toolbar.html
- peachjam/templates/peachjam/_document_floating_header.html
- peachjam/templates/peachjam/layouts/document_detail.html
- peachjam/templates/peachjam/saved_document_create.html
- peachjam/templates/peachjam/saved_document_login.html
- peachjam/templates/peachjam/saved_document_update.html
This adds a floating titlebar at the top of a document that is shown when the user scrolls past the title of the document. This means the title is always visible, and gives us a place to put key action buttons (for now, just "save").
The navigation toggle in mobile moves into the title bar and takes up less room.
The save button is adjust so that it uses htmx's oob-swap functionality to replace all `.save-document-button` instances on the page, not just the one in the main toolbar.
The "save document" button text is adjusted to support smaller widths.
https://www.loom.com/share/019b164cde2242e7a624ab1bbb6a13cb
> Floating titlebar above document

- peachjam/js/components/clipboard.ts
- peachjam/static/stylesheets/components/_document-content.scss
- peachjam/templates/peachjam/_copy_to_clipboard.html
- peachjam/templates/peachjam/_document_floating_header.html
- peachjam/templates/peachjam/judgment_detail.html
- peachjam/templates/peachjam/layouts/document_detail.html
* the button is only visible on desktop, because there isn't enough room on mobile and the need for copying the citation on mobile is much less
> Copy citation button for floating toolbar

- peachjam/admin.py
- peachjam/decorators.py
- peachjam/models/core_document.py
- peachjam/models/judgment.py
- peachjam/models/legislation.py
- peachjam/templates/peachjam/layouts/document_detail.html
Decorators moves the site-specific label decoration into a mini plugin class, which can be overridden/changed by other sites.
Also make it possible to override the alternative names label in the document detail page.
> Decorators

- peachjam/forms.py
- peachjam/static/stylesheets/components/_tables.scss
- peachjam/templates/peachjam/_document_table.html
- peachjam/templates/peachjam/_document_table_row.html
- peachjam/tests/test_forms.py
- peachjam/tests/test_views.py
- peachjam/views/generic_views.py
- peachjam/views/legislation.py
Where necessary, use the work year for facets and ordering.
https://www.loom.com/share/05b52faa01eb4d95b4ab7472b0bc2e67
* make filtering in the filter form more customisable
* use the year portion of `frbr_uri_date` rather than the `date` field in many legislation listing views
* add overrides for filtering and grouping in legislation list views
* facet by frbr_uri_date
* update `.doc-table` CSS so that it handles lack of a date column (previously this was always assumed to be present)
* bonus: add a tooltip and a group title for "Subsidiary legislation" in the expanded children view
> Remove dates from legislation listing views

- peachjam/templates/peachjam/_document_floating_header.html
> don't allow buttons to wrap in floating toolbar

- peachjam/templates/peachjam/_document_table_row.html
- peachjam/templates/peachjam/_document_taxonomies.html
- peachjam/templates/peachjam/document_popup.html
fixes #2263
(the "lawlibrary" won't be shown in production)
> show taxonomies in document popup

- app.json
https://github.com/laws-africa/peachjam/actions/runs/13784035528/job/38549008005
> fixes checks

- peachjam/templates/peachjam/document/social_image.html
* bigger fonts
* move date into footer to make better use of that space
* smaller footer logo height
* remove taxonomy tags, they are too difficult to plan around since they vary so hugely
* add court for judgments
> simplify social image and use bigger fonts

- peachjam/js/components/DocDiffs/index.ts
- peachjam/js/components/analytics.ts
This is a start of us tracking non-page interactions (see #1619)
Events: https://docs.google.com/spreadsheets/d/1TO0B92dBuheOi_RmenL3Tkh7kSo9G2RyLRcjG8Fn2So/edit?gid=0#gid=0
Docs: https://matomo.org/faq/reports/implement-event-tracking-with-matomo/
> Track an event for the "What changed" button

- peachjam/js/components/analytics.ts
matomo then ignores them, rather than using nulls
> trackEvent name and value can be undefined

- peachjam/js/components/analytics.ts
- peachjam/js/peachjam.ts
otherwise, our local ref is an array but when matomo loads it replaces window._paq with a function, our local ref won't have it
> lazy reference to paq and gtag

- peachjam/resources.py
somehow a matter type with a blank name was created, which is not possible through the admin UI, so must have come from a bulk import
> guard against creating blank matter types

- lawlibrary/templates/peachjam/about.html
- peachjam/forms.py
- peachjam/templates/peachjam/emails/document_problem_email.html
- peachjam/templates/peachjam/emails/document_problem_email.txt
* on lawlibrary, replace the contact form with the helpscout widget
* use SUPPORT_EMAIL as a backup for lawlibrary
* when submitting problem reports, use the user's email as the from address to support direct reply
* tweak problem email templates
> helpscout widget, use SUPPORT_EMAIL for lawlibrary.org.za

- peachjam/js/components/Anon/AnonApp.vue
- peachjam/js/components/Anon/ReplacementGroupDetail.vue
- peachjam/js/components/Anon/SuggestionsPane.vue
since they are injected into all pages, they break other functionality
> scope styles for AnonApp

- peachjam_search/models.py
Avoids email subject lines such as:
```
New matches for your search: EVOLV OUTDOOR (-date)
```
> exclude sort key from saved search pretty filters

- peachjam/static/stylesheets/_variables.scss
- peachjam/templates/peachjam/_document_table_form.html
It has been bugging me that it doesn't use the full screen width when my phone is in landscape mode. I don't see any reason to limit the width to breakpoints until the page gets as wide as a desktop.
> Bootstrap container is fluid up to container-lg

- peachjam/models/citations.py
- peachjam_ml/views.py
Get the top 100 documents by similarity, then re-rank using authority, and show the top 10.
Motivation for re-ranking, rather than folding the authority into the score during querying:
1.	Semantic similarity is the primary signal — the user expects the results to be on-topic first.
2.	Authority is a tie-breaker — we want to show the most valuable among the relevant.
3.	We avoid accidentally discarding high-similarity docs with lower authority.
Also:
1. sort citation lists by authority, rather than just citations
> use authority to re-rank similar documents and order citations

- peachjam/js/components/DocumentContent/pdf-renderer.ts
- peachjam/static/stylesheets/components/_document-content.scss
- peachjam/templates/peachjam/_document_content.html
* show an error when the PDF fails to load, rather than letting the user watch a spinner go nowhere
* load the pdf data using fetch() so that we have visibility into what went wrong
* if the response is a non-200 response, then raise an exception so we get a sentry alert
> Better PDF error handling

- peachjam/static/stylesheets/_variables.scss
- peachjam/static/stylesheets/components/_header.scss
- peachjam/static/stylesheets/components/_text.scss
- peachjam/templates/account/_social_login_buttons.html
- peachjam/templates/account/login.html
- peachjam/templates/account/signup.html
- peachjam/templates/peachjam/_open_law_africa.html
- peachjam/templates/peachjam/layouts/document_detail.html
- peachjam/templates/peachjam/user_following/_timeline.html
* move social login buttons to top of login and sign up pages, since they are by far the most used login mechanism
* reduce size of OLA header
* reduce padding on alerts to take up less room
* normalise margins on document title and reduce font size
* add an xxxl breakpoint at 1600px for very wide screens to take advantage of the extra width
* drop sticky-top on timeline, it looks weird
> Visual and layout tweaks

- peachjam_ml/admin.py
- peachjam_ml/models.py
- peachjam_ml/tests/test_content_chunks.py
when we break an AKN document into chunks, we do it recursively. This
gives us good coverage and semantic search across provision boundaries
as well as accuracy when finding provision-level matches.
When we're calculating the average of all a document's chunks to find
the document-level embedding, we don't want to include the repeated
(nested) chunks because it gives them more weight than they should have.
Instead, use the average of the top-level provisions.
> Fix bug that skewed legislation document embeddings

- peachjam/js/components/DocumentContent/ShareSelectionModal.vue
- peachjam/js/components/index.ts
- peachjam/js/components/share-menu-item.ts
- peachjam/templates/peachjam/_document_detail_toolbar.html
- peachjam/templates/peachjam/layouts/document_detail.html
- peachjam/templates/peachjam/saved_document/_create.html
- peachjam/templates/peachjam/saved_document/_update_button.html
* move Save button to the left and make it primary so it stands out
* make download button secondary
* on mobile, move share, download and report a problem into a dropdown menu to preserve space
> Adjust document detail page toolbar and use menu on mobile

- peachjam/static/stylesheets/components/_tables.scss
- peachjam/templates/peachjam/document/_citations_list.html
make them flush, remove last border
> improve look of document tables in cards

- peachjam/js/components/FilterFacets/index.vue
- peachjam/js/components/FindDocuments/FacetBadges.vue
- peachjam/js/components/FindDocuments/MobileSideDrawer.vue
- peachjam/js/components/FindDocuments/index.vue
- peachjam/static/stylesheets/_global.scss
- peachjam/static/stylesheets/components/_navs.scss
- peachjam/templates/peachjam/layouts/document_detail.html
Reduce clutter on search page, particularly on mobile:
* move sort into filter fly-out
* make sort dropdown take up less space
* move label into the dropdown
* hide faceting buttons in mobile view (they take up too much space, and can be found in the filtering fly-out)
Also:
* tweak placement of star in document detail page so that it's to the right of the title, not at the end of a wrapped line
> Simplify search view (in particular on mobile)

- peachjam/templatetags/peachjam.py
- peachjam_search/templates/peachjam/emails/search_alert.email
Closes #2522
To prevent a hit without highlights, I included cases for pages and provisons
> Include matching text snippet in search alert emails

- .github/workflows/deploy.yml
this changes the order of deployments. we are now deploying 2 sites at a time on web2
> change the order of deployments

- liiweb/templates/liiweb/legislation_list.html
- peachjam/js/components/ProvisionEnrichments/ProvisionEnrichment.vue
- peachjam/static/stylesheets/_variables.scss
- peachjam/static/stylesheets/components/_enrichments.scss
- peachjam/static/stylesheets/components/_icons.scss
- peachjam/templates/peachjam/document/_uncommenced_provisions.html
- peachjam/templates/peachjam/document/_unconstitutional_provisions.html
- peachjam/templates/peachjam/layouts/document_detail.html
- peachjam/views/legislation.py
> Uncommenced provisions tweaks

- peachjam/analysis/citations.py
- peachjam/tests/test_xmlutils.py
- peachjam/xmlutils.py
* adds utilities to extract preceding and following text content, without going above certain tags
This makes it difficult to have accurate "start" and "end" position counts for the offset within the document / to the anchor element. If we need that, then we need to find the text relative to the anchor element from the very start.
We don't strictly need the selector details, we only need the prefix and suffix text. I think we can safely exclude that information for now.
> utils to collect preceding and following node text

- peachjam/templates/peachjam/layouts/document_detail.html
> Removed type field in document metadata

- peachjam_ml/models.py
Closes #2542 
@actlikewill I'd have had to repeat the Coredocuments mapping for the folder view, so I chose to filter from the base function.
The before and after
> show only latest expression in suggested documents

- peachjam/adapters/indigo.py
- peachjam_api/views.py
Otherwise no authentication takes place at all and all requests fail. Token authentication (the default) ignores unauthenticated requests which is what we need for certain secret-based webhooks
> fix bug that prevented webhooks from authenticating

- peachjam/templates/peachjam/layouts/document_detail.html
this blows up the number of pages crawlers index, and makes our sites look like they have lots of duplicate content
> tell robots not to index historical versions

- peachjam/js/components/DocumentContent/pdf-renderer.ts
> don't record 404s as errors when fetching PDFs
