laws-africa/peachjam

- .github/workflows/build-l10n.yml
This workflow automates the updating of .po files to .mo files.
> Add translation build workflow

- africanlii/templates/africanlii/legislation_detail.html
Broken due to a missing i18n tag
Fix for [PEACHJAM-STAGING-F](https://sentry.io/organizations/lawsafrica/issues/3345612647/?project=6248807&referrer=slack)
> Fix Legislation Detail Page

- africanlii/templates/africanlii/_document_table.html
> Adjustments to document listing tables

- peachjam_search/views.py
This PR disables auth requirement on the search API view
> Disable Auth on Search API

- africanlii/views/home.py
Document count =  judgment doc count + generic doc count  + legal instrument count + legislation count
> Total document count on home page

- .github/workflows/test.yml
- Dockerfile
- peachjam/admin.py
- peachjam/settings.py
- requirements.txt
> Add ckeditor to admin

- africanlii/views/generic_views.py
add logic to filter out items in the authors iterable that are not truthy. This ensures  `ListFacets.vue` does not break as it expects truthy values
resolves #237
> Filter out values that are not true for authors facet

- peachjam/resources.py
- Tweaks to the judgments resource 
- Serial number for judgment
> Judgment resource

- peachjam/models/core_document_model.py
fixes validation for frbr uris
> Validation for frbr uri

- africanlii/static/stylesheets/_document-content.scss
- africanlii/static/stylesheets/_global.scss
- peachjam/js/components/DocumentSearch/index.vue
- peachjam/js/components/document-content.ts
- peachjam/js/components/pdf-renderer.ts
- peachjam/js/utils/function.ts
- peachjam/templates/peachjam/_document_content.html
- Created improved  scrollToElement function. This is a function that returns a promise, when operation of scrolling to the element is finished the promise is resolved. The intersection observer is used to determine this 
**Solution:** 
Virtual keyboard on mobile was triggering the resize callback, has `placeContent` was triggering. We stop this by checking if window resize was triggered by device virtual keyboard and if stop the callback
**Solution:**  Use scrollToElement
**Solution:**  Use scrollToElement
DEMO:
https://www.loom.com/share/49621daec82c4d0cbcfed116bb07739a
resolves #262
> Mobile fixes

- africanlii/forms.py
- africanlii/templates/africanlii/_document_table.html
- peachjam/js/components/ListFacets.vue
- peachjam/templates/peachjam/home.html
- peachjam/views/generic_views.py
- peachjam/views/home.py
- Change "Author" to Regional Body" in homepage and in filter facets
- Order recent document list by document date
- Show Regional Body, rather than jurisdiction in document lists that show jurisdiction
- When showing document type in listing views, needs to be user-friendly document type
- Selecting multiple years in the document facet view now shows documents with all years
> Minor changes:

- peachjam/admin.py
This is a reasonable default and can be changed by the user.
> Pre-populate frbr_uri_number from slugified title

- peachjam/models/judgment.py
- Fixes a bug where the mnc is not assigned correctly on judgments
> Fixes mnc assignment operation

- africanlii/apps.py
- requirements.txt
Depends on [docpipe #3](https://github.com/laws-africa/docpipe/pull/3) 
* **Source document:**
* **Marked up citations:**
> ActMatcher

- peachjam/js/components/FindDocuments/index.vue
> Show years in descending order for search page

- lawlibrary/templates/lawlibrary/court_detail.html
- lawlibrary/templates/lawlibrary/judgment_list.html
- lawlibrary/templates/peachjam/header.html
- lawlibrary/templates/peachjam/layouts/document_detail.html
- lawlibrary/urls.py
- liiweb/templates/liiweb/_judgment_table.html
- peachjam/js/components/ListFacets.vue
- peachjam/models/judgment.py
- peachjam/static/stylesheets/components/_document-content.scss
- peachjam/templates/peachjam/_recent_document_list.html
- peachjam/templates/peachjam/generic_document_detail.html
- peachjam/templates/peachjam/judgment_detail.html
- peachjam/templates/peachjam/layouts/document_detail.html
- peachjam/templates/peachjam/layouts/document_list.html
- peachjam/templates/peachjam/legal_instrument_detail.html
- peachjam/templates/peachjam/legislation_detail.html
* detail page: judges, change "author" to court, breadcrumbs
* bug: judge filters don't stick
* court judgment list columns
* judgment listing page move header left
* recent documents list columns
> Page adjustments

- peachjam/adapters/adapters.py
> Fixes locality bug in indigo adapter

- peachjam/adapters/adapters.py
> Fixes doc subtype in adapter

- lawlibrary/templates/lawlibrary/legislation_list.html
- lawlibrary/templates/lawlibrary/provincial_legislation_list.html
- lawlibrary/templates/peachjam/header.html
- peachjam/js/components/LegislationTable/SecondaryFacets.vue
- peachjam/js/components/LegislationTable/SingleFacet.vue
- peachjam/js/components/LegislationTable/index.vue
- peachjam/js/components/index.ts
- Created `LegislationTable/index.vue` to display Legislation data
- Implemented search functionality in component
- Implemented sorting (ascending or descending) by column heading
- Implemented filtering using `SecondaryFacets.vue` 
- Added mobile support. SecondaryFacets are displayed Offcanvas element on mobile view
DEMO:
https://www.loom.com/share/a7de2bde771742c5b044ba7270a98630
> Legislation table vue and styling

- peachjam/js/components/FindDocuments/SearchResult.vue
- peachjam/js/components/document-content.ts
- peachjam/js/components/pdf-renderer.ts
- peachjam/js/utils/function.ts
- peachjam_search/documents.py
- peachjam_search/serializers.py
- peachjam_search/views.py
DEMO:
https://www.loom.com/share/bff6768dcf864ba7828d352ac9324c8a
closes #300
> Page based indexing for pdfs

- peachjam/migrations/0001_initial.py
- peachjam/settings.py
- peachjam_search/tasks.py
> Handle ES indexing tasks in the background.

- peachjam/js/components/pdf-renderer.ts
- peachjam/static/stylesheets/components/_document-content.scss
- peachjam/templates/peachjam/_document_content.html
Add logic to include prompt if pdf file is large
Demo:
https://www.loom.com/share/3359323674114bd59df2dc7585b0152d
resolves https://github.com/laws-africa/peachjam/issues/356
> Handling large pdf

- README.md
Prerequisites needed before setting up peachjam.
> add prerequisites to readme.md

- peachjam/adapters/adapters.py
- peachjam/settings.py
- peachjam/templates/peachjam/_notices.html
- peachjam/templates/peachjam/_recent_document_list.html
- peachjam/templates/peachjam/layouts/document_detail.html
- peachjam/views/legislation.py
- Display notices 
- Add the text-nowrap class to prevent dates in the recent documents table from wrapping
> Fix notices

- peachjam/resources.py
- adds auto creation of authors on bulk import
> Auto creation of authors on bulk import

- peachjam/models/core_document_model.py
- peachjam/urls.py
- peachjam/views/documents.py
- peachjam/views/generic_views.py
* store images
* serve them when rendering
> Store image attachments when importing

- lawlibrary/forms.py
- lawlibrary/views/court.py
- peachjam/views/generic_views.py
https://www.loom.com/share/e70d4cd91eb94567845ddcdd6a712f84
> Court view can filter on judge name

- peachjam/templates/peachjam/_pagination.html
- peachjam/templatetags/peachjam.py
- Adds ellipsis to pagination for long lists.
closes #396
> Fix pagination for long lists

- peachjam/js/components/clipboard.ts
- peachjam/js/components/index.ts
- peachjam/static/stylesheets/_global.scss
- peachjam/templates/peachjam/layouts/document_detail.html
https://www.loom.com/share/ae2b5ee215f043cab4eeba268dcc6c96
> Citation with copy-to-clipboard

- peachjam/resources.py
> Fix resources for sca upload

- lawlibrary/templates/lawlibrary/court_detail.html
- liiweb/templates/liiweb/_judgment_table.html
- peachjam/templates/peachjam/judgment_detail.html
- peachjam/templates/peachjam/layouts/document_detail.html
- peachjam/views/legislation.py
* include MNC in judgment detail
* include case numbers in judgment detail
* show download extension
* show additional PDF download if the original document isn't a pdf
> MNC, case numbers, download extension, download PDF

- lawlibrary/templates/lawlibrary/_early_preview_warning.html
- lawlibrary/templates/lawlibrary/_legislation_alert.html
- lawlibrary/templates/lawlibrary/legislation_list.html
- lawlibrary/templates/lawlibrary/provincial_legislation_list.html
- lawlibrary/templates/peachjam/header.html
> Early preview warnings

- peachjam/adapters/adapters.py
- Get or create author in adapter.
fixes #424
> Create author in adapter

- peachjam/templates/peachjam/layouts/document_detail.html
Without relationships
With relationships
> Fix wrapping on document detail page

- lawlibrary/templates/lawlibrary/court_detail.html
- lawlibrary/templates/lawlibrary/judgment_list.html
- lawlibrary/templates/lawlibrary/legislation_list.html
- lawlibrary/templates/lawlibrary/provincial_legislation.html
- lawlibrary/templates/lawlibrary/provincial_legislation_list.html
- lawlibrary/templates/peachjam/judgment_detail.html
- lawlibrary/templates/peachjam/legislation_detail.html
- peachjam/static/stylesheets/_global.scss
- peachjam/templates/peachjam/generic_document_list.html
- peachjam/templates/peachjam/judgment_list.html
- peachjam/templates/peachjam/layouts/document_detail.html
- peachjam/templates/peachjam/layouts/document_list.html
- peachjam/templates/peachjam/legal_instrument_list.html
- peachjam/templates/peachjam/legislation_list.html
- Add refactor margin classes for pages
- Add light background for header element on document detail page
DEMO:
https://www.loom.com/share/068bf961fe114bb48053c8b558d773c6
resolves https://github.com/laws-africa/peachjam/issues/430
> UI consistency accross pages

- peachjam/static/stylesheets/components/_document-content.scss
- peachjam/templates/peachjam/layouts/document_detail.html
https://www.loom.com/share/c092e711d6b74bdab1514dbb2d92a75a
resolves https://github.com/laws-africa/peachjam/issues/486
> Key pair meta block spacing

- peachjam/templates/peachjam/_document_content.html
resolves https://github.com/laws-africa/peachjam/issues/509
> change text from PDF Preview to Pages

- lawlibrary/templates/peachjam/_header.html
- lawlibrary/templates/peachjam/about.html
DEMO:
https://www.loom.com/share/f1c30c4c2f44483e8c42a14a1db40bd1
resolves https://github.com/laws-africa/peachjam/issues/464
> Create about page and add contact form

- peachjam/static/stylesheets/components/_document-content.scss
- peachjam/templates/peachjam/_document_content.html
- peachjam/templates/peachjam/layouts/main.html
> button to jump to the top

- peachjam_search/views.py
This PR fixes [AGP-2C on Sentry](https://sentry.io/share/issue/5570b724fd3040a28c8a814ecb238eb9/)
> Search Ordering by Date Fix

- peachjam/settings.py
- peachjam/static/stylesheets/_variables.scss
- peachjam/templates/peachjam/layouts/document_detail.html
- peachjam_search/documents.py
These are necessary to migrate Gazettes.Africa onto peachjam.
> make some settings easier to override

- peachjam/views/generic_views.py
https://www.loom.com/share/78a869015e964d59aa9c038305386e9a
> Fix year filter facet

- .github/workflows/test.yml
- peachjam/resources.py
- peachjam/tests/test_bulk_import.py
- Standardize the judgments bulk import resource esp. as regards to case numbers.
> Judgment  import resource update

- peachjam/views/courts.py
> Add year facet filter to court detail view

- peachjam/admin.py
- Fixes validation for date widget.
This allows judgements to be saved without hearing date.
> Fixes date widget validation for empty dates

- lawlibrary/templates/peachjam/legislation_detail.html
> Fix Legislation detail breadcrumb logic

- peachjam/settings.py
> Allow xframes

- peachjam/download.py
- peachjam/resources.py
- peachjam/tests/test_bulk_import.py
- Adds Skip Widget for skipping rows
- Adds source file widget for validating source files
- Refactors getting case numbers and source file logic into class methods
- Fixes tests
> Bulk Import resource tweaks

- peachjam/js/components/FilterFacets/SingleFacet.vue
- peachjam/js/components/FindDocuments/index.vue
- peachjam_search/views.py
* up cap on max facets
* scroll tall facets
* don't show "Filters" heading if no search results
Closes #615 
https://www.loom.com/share/2a7e1b1dc8db42dc9387d8ae1f2abf8d
> Facet size

- peachjam/resources.py
- peachjam/tests/test_bulk_import.py
- adds mutilple case string override in resource
> Multiple case string overrides

- peachjam/views/authors.py
- peachjam/views/legal_instrument.py
> Optimize query for author listing page and legalinstruments

- peachjam/views/generic_document.py
> Optimize query for generic documents

- peachjam_search/views.py
Allows all types of filtering on date
> Allow date filtering

- peachjam/views/generic_document.py
Reverts laws-africa/peachjam#633
> Revert "Optimize query for generic documents"

- peachjam/resources.py
- peachjam/tests/test_bulk_import.py
- Adds validation for bulk import resources
> Resource validation

- peachjam/js/components/document-content.ts
- peachjam/views/generic_views.py
* ids for headings
* don't rewrite `data:` images
Closes #629
> ids for headings; don't rewrite data: images

- peachjam/forms.py
- adds slugify to source file name.
> Slugify source file

- pyproject.toml
This will use sass caching and should make local dev faster
> django-sass-processor-dart-sass 0.1.0

- peachjam/admin.py
- peachjam/forms.py
* slugify to strip colons when uploading a new source file
* fix defaulting `frbr_uri_date` from `date` field
> Colons, dates

- peachjam/resources.py
- Fixes skip rows in bulk imports.
> Fix skip rows in bulk imports

- peachjam/forms.py
- peachjam/storage.py
otherwise slashes and dots are removed. This can safely be done multiple times.
> replace colons rathing than using slugify

- peachjam/adapters/adapters.py
- peachjam/models/ingestors.py
- peachjam/settings.py
- peachjam/tasks.py
- peachjam_api/permissions.py
- peachjam_api/serializers.py
- peachjam_api/urls.py
- peachjam_api/views.py
- Adds an endpoint to update a document using the indigo ingestor.
> Indigo webhook

- peachjam/templates/peachjam/court_detail.html
> Wrap year list

- peachjam/forms.py
- Adds functionality to re extract content when source file is changed.
closes #658
> Reextract content on source file change

- peachjam/resources.py
- peachjam/tests/test_bulk_import.py
- Adds better error handling for bulk imports
closes #673
closes #675
closes #676
> Bulk import error handling

- peachjam/resources.py
- Sometimes the importer sets the data type of the numbers as floats. 
- We need to cast them to string and ints.
> Datatypes for case_numbers import

- peachjam/static/stylesheets/components/_entity-profile.scss
- peachjam/static/stylesheets/components/_index.scss
- peachjam/templates/peachjam/_entity_profile.html
- peachjam/templates/peachjam/author_detail.html
- peachjam/templates/peachjam/court_detail.html
- peachjam/templates/peachjam/layouts/document_list.html
- peachjam/templates/peachjam/taxonomy_detail.html
- peachjam/views/courts.py
Demo:
https://www.loom.com/share/3adbd045e9144599b6ca26f9ba8e5a95
Added entity profiles to the following pages:
- court detail
- author detail
- taxonomy detail
> Entity profile front end

- peachjam/adapters/adapters.py
> Fix existing doc

- africanlii/urls.py
Fixes https://github.com/laws-africa/peachjam/issues/712
> Fix legislation list view on AfricanLII

- peachjam/fixtures/tests/languages.json
- peachjam/models/judgment.py
- peachjam/tests/test_judgment.py
> localise date for judgment titles

- pyproject.toml
> Pin django nine to version 0.2.5

- peachjam/js/components/FindDocuments/index.vue
- peachjam/js/locale/en/translation.json
- peachjam/js/locale/fr/translation.json
- peachjam/js/locale/sw/translation.json
resolves https://github.com/laws-africa/peachjam/issues/722
> translate "Search" and "Advanced search"

- peachjam/templates/peachjam/taxonomy_detail.html
- peachjam/views/taxonomy.py
- senlii/locale/en/LC_MESSAGES/django.po
- senlii/locale/fr/LC_MESSAGES/django.po
- senlii/locale/pt/LC_MESSAGES/django.po
- senlii/locale/sw/LC_MESSAGES/django.po
- senlii/templates/peachjam/_header.html
> Don't show empty taxonomy tree; link to taxonomy in senlii

- peachjam/static/stylesheets/components/_entity-profile.scss
- peachjam/templates/peachjam/_child_documents.html
- peachjam/templates/peachjam/_document_table.html
- peachjam/templates/peachjam/_entity_profile.html
- peachjam/templates/peachjam/_judgment_table.html
DEMO:
https://www.loom.com/share/06c0e6e1da75444aa6e4fc70096de29b
> Restyle banner of entity profile

- peachjam/adapters/__init__.py
- peachjam/adapters/gazettes.py
- peachjam/settings.py
- Adds and ingestor for gazettes
> Gazettes ingestor

- peachjam/views/legislation.py
- fixes legislation amendments
-
> fixes legislation amendments

- peachjam/templates/peachjam/top_level_taxonomy_list.html
Screenshot:
resolves https://github.com/laws-africa/peachjam/issues/745
> top-level taxonomy view show second level

- peachjam/views/authors.py
- peachjam/views/generic_document.py
- peachjam/views/judgment.py
- peachjam/views/legal_instrument.py
Prefetch related work for `/generic_documents/`, `/legal_instruments/`, `/judgments/` and `/authors/{pk}/`
Before:
After:
Before:
After:
Before:
After:
Before:
After:
> Prefetch related work

- peachjam/templates/peachjam/layouts/document_detail.html
- Make social share icons wrap on mobile
DEMO:
https://www.loom.com/share/d23f5ffe6b73448cb2b8344d2f846196
> Add responsive classes to social share html

- peachjam/adapters/adapters.py
- Capitalize document nature name in adapter
closes laws-africa/peachjam#723
> Capitalize document nature name in adapter

- peachjam/pipelines.py
- peachjam/resources.py
> RTF files in bulk import

- peachjam/admin.py
- Fixes the readonly fields in the source file admin
Fixes #806
> Fixes source-file readonly fields bug

- peachjam/models/core_document_model.py
- peachjam/resources.py
This PR adds functionality for importing multiple alternative names/citations.
Closes: https://github.com/laws-africa/peachjam/issues/788
Demo:
https://www.loom.com/share/bec2aa316624417c8fa17f6dc03a5b47
> Add functionality for importing multiple alternative names/citations

- lawlibrary/templates/lawlibrary/_legislation_alert.html
- lawlibrary/templates/peachjam/about.html
This PR updates the legislation notice to allow users to tell the admin what they're missing.
Closes #822 
Demo:
https://loom.com/share/a2730b72ca9141f99d7019805d76b1f3
> Update legislation notice

- peachjam/adapters/adapters.py
* Fixes LAWLIBRARY-25 in sentry
* removes duplication of document nature setup
> Simplify import logic, remove duplicate code

- liiweb/settings.py
- liiweb/urls.py
- liiweb/views/__init__.py
- liiweb/views/redirect.py
- ulii/settings.py
- ulii/urls.py
- ulii/views/__init__.py
- Redirect old lii case urls to peachjam urls
closes #792
> Redirects old lii case urls to peachjam liis

- peachjam/context_processors.py
- reenable settings in context
> renable settings in context

- peachjam_search/views.py
Before:
Note that before:
1.  the top match is not related to the protocol at all
2. there is no "protocol" in the document type list
After:
Note that afterwards:
1. the top matches are strong matches on document title
4. there are a diversity of document types, including "Protocol"
> Search using AND within fields, but OR between fields

- peachjam/admin.py
- peachjam/templates/peachjam/_entity_profile.html
Currently we have to edit as a raw HTML field
> Entity profile ckeditor

- liiweb/templates/liiweb/legislation_list.html
- moves the subleg link position
> Change subleg link position

- peachjam/resources.py
- peachjam/tests/test_bulk_import.py
- Adds taxonomies in bulk import.
- Adds validation for missing taxonomies while doing bulk import.
> Taxonomies in bulk import

- lawlibrary/templates/lawlibrary/home.html
- lawlibrary/views/home.py
- peachjam/templates/peachjam/_taxonomy_list.html
- peachjam/templates/peachjam/top_level_taxonomy_list.html
> Add collections to lawlibrary homepage

- .github/workflows/deploy.yml
- enable ghalii deployment action
> Ghalii deployment action

- .github/workflows/deploy.yml
> Zambialii deployment action

- peachjam/templates/peachjam/layouts/document_detail.html
- peachjam/templates/peachjam/layouts/main.html
pdfjs generates lots of spurious errors which we have no control over also, load pdfjs only on doc page
> ignore pdfjs in sentry

- .github/workflows/deploy.yml
Sets concurrency for deployment actions to minimize server load during deployment.
> Concurrency for deployment actions

- .github/workflows/deploy.yml
> fixes deploy

- .github/workflows/deploy.yml
> Lesotholii deploy

- .github/workflows/deploy.yml
- Change deployment url to liiweb2
> Deploy to liiweb2

- liiweb/apps.py
- peachjam/admin.py
- peachjam/analysis/citations.py
- peachjam/settings.py
- peachjam/tasks.py
* updates the citation extraction step to call the new Laws.Africa citator service, if API details are provided
* background task to update citations
* background task to re-index for search
> Call citator service

- peachjam/models/taxonomies.py
- peachjam/tests/test_bulk_import.py
- changes taxonomy slug to include parent slug
> Taxonomy slug to include parent slug

- peachjam/views/generic_views.py
- The logic for rendering the nature facet was faulty.
> Fixes doclist nature filter facet

- peachjam/admin.py
- peachjam/forms.py
- peachjam/models/core_document_model.py
Otherwise, the main object main not be saved yet.
Extract mimetype no matter what, otherwise changing source files through the admin form doesn't change the mime type.
I've tested with uploading a new file, deleting and adding a source file, and changing a source file directly.
> Process related objects in save_m2m

- africanlii/templates/peachjam/_header.html
- peachjam/static/bootstrap/scss/_variables.scss
- peachjam/static/stylesheets/components/_navbar.scss
- peachjam/templates/peachjam/_years_list.html
- Issue https://github.com/laws-africa/peachjam/issues/909
- Loom https://www.loom.com/share/ae3fb5c4b1584084a65b628d31a88b1c
- Navigation didn't look good on screens from 992px to around 1030px so I increased the max width of screens over 992px by 10px. I can revert changes if you think it is unnecessary.
Before the change:
After the change on the same width as above:
> New top-level navigation on AGP

- peachjam/views/place.py
> Optimize query

- peachjam/adapters/gazettes.py
> Gazettes nature

- .github/workflows/deploy.yml
> Lii deployment scripts

- africanlii/templates/peachjam/_header.html
- africanlii/templates/peachjam/generic_document_list.html
- africanlii/templates/peachjam/reports_guides_list.html
- africanlii/templates/peachjam/soft_law_list.html
- africanlii/urls.py
- africanlii/views.py
- peachjam/templates/peachjam/legal_instrument_list.html
closes #906 
closes #907
closes #908
> AGP legal instrument list view 

- africanlii/templates/peachjam/_header.html
- africanlii/views.py
> Fix agp header links

- peachjam/views/gazette.py
- Fixes the bug that prevents all listed gazettes from showing.
> Fix gazette listing page

- peachjam/views/gazette.py
- fixes filtering on gazette locality
> Fix gazette locality

- peachjam/adapters/gazettes.py
- add extract citation for gazettes ingestor
> Extract citation for gazettes ingestor

- .github/ISSUE_TEMPLATE/config.yml
Add configuration for issue template chooser.
> Configure issue template

- liiweb/views/legislation.py
Resolves https://github.com/laws-africa/peachjam/issues/888
> Change filter for current legislation

- peachjam/admin.py
> Add list display fields for court registry

- peachjam/adapters/adapters.py
> Walk results pages in indigo adapter

- africanlii/templates/peachjam/terms_of_use.html
- lawlibrary/templates/peachjam/terms_of_use.html
- namiblii/templates/peachjam/_footer.html
- namiblii/templates/peachjam/terms_of_use.html
- peachjam/templates/peachjam/_terms_of_use_content.html
> Namiblii terms-of-use

- peachjam/js/components/DocumentContent/index.ts
- peachjam/js/components/DocumentSearch/index.vue
- peachjam/js/components/FindDocuments/SearchResult.vue
- Issue https://github.com/laws-africa/peachjam/issues/861
- Loom https://www.loom.com/share/cc4d41c523a2424d855f91e490ae767e
> Disable functionality to include search in per-document links in search results

- peachjam/js/components/FindDocuments/index.vue
- peachjam/js/components/ListFacets.vue
- Removes registry from search
```
http://127.0.0.1:8001/search/api/documents/?search=children&page=1&ordering=-score&highlight=content&
is_most_recent=true&facet=doc_type&facet=author&facet=court&facet=judges&facet=attorneys&facet=jurisdiction&
facet=locality&facet=matter_type&facet=nature&facet=language&facet=year
```
closes #1028
> Removes court registry from search

- africanlii/templates/peachjam/home.html
- africanlii/views.py
- peachjam/views/home.py
> Agp homepage

- peachjam/templates/peachjam/layouts/document_detail.html
> Change "Date" label to "Judgment date" for judgment document detail page

- peachjam/admin.py
- peachjam/resources.py
- adds bulk import for Articles
closes #1037
> Bulk import for Article model

- peachjam/templates/peachjam/author_detail.html
> Add document count to author detail page

- peachjam/views/legislation.py
> Show warnings for unapplied amendments

- peachjam/views/legislation.py
> Add notice for uncommenced legislation

- peachjam/templates/peachjam/layouts/document_detail.html
> Fix judges list

- peachjam/admin.py
- peachjam/resources.py
- peachjam/settings.py
- peachjam/templates/account/login.html
- peachjam/templates/admin/login.html
This PR adds:
- E-mail configuration
- Functionality for bulk importing users
> Add support for bulk importing users

- africanlii/settings.py
- peachjam/settings.py
- peachjam/tests/test_resolver.py
- peachjam/views/documents.py
- peachjam_search/views.py
- Adds search across multiple indexes
https://www.loom.com/share/25b8fb3b4fc94c039d82cc618dc921b6
closes #498
> Search across multiple indexes

- africanlii/templates/peachjam/_header.html
> Fixes broken link for agp

- africanlii/templates/peachjam/home.html
- namiblii/templates/peachjam/_header.html
- peachjam/templates/peachjam/layouts/document_detail.html
- peachjam/urls.py
- peachjam/views/authors.py
> Add NamibLII law reform menu item

- .eslintrc.js
- peachjam/js/components/FindDocuments/AdvancedSearch.vue
- peachjam/js/components/FindDocuments/AdvancedSearchFields.vue
- peachjam/js/components/FindDocuments/index.vue
* remove unused advanced search fields to simplify things for now
* group fields so the interface is less overwhelming
* order fields to put common ones at the top
* include all search info in page state
* support push/popstate to support browser navigation
> Advanced search

- liiweb/views/general.py
- peachjam/templates/peachjam/_court_list.html
- peachjam/tests/test_views.py
- peachjam/views/judgment.py
This PR tweaks the court class and court ordering code.
> Tweak court class and court ordering

- peachjam/graph/ranker.py
> Fix gds ranking property

- tcilii/templates/liiweb/home.html
- tcilii/templates/peachjam/_footer.html
- zambialii/templates/liiweb/home.html
closes #1120
closes #1121
closes #1151
> TCILII and ZambiaLII tweaks

- tcilii/templates/peachjam/_footer.html
Adds the mailchimp form action code necessary for newsletter to work
> Add mailchimp config for TCILII newsletter

- zimlii/templates/peachjam/_header.html
> Add ZimLII collections menu

- CHECKS
> disable checks

- CHECKS
- peachjam/context_processors.py
- disabling settings to allow deploy
> disable settings

- peachjam/js/components/FindDocuments/AdvancedSearch.vue
https://github.com/laws-africa/peachjam/assets/52611827/2785a09c-31f9-4979-a35e-9169c5fd177d
> Fixed incorrect search state

- seylii/templates/liiweb/home.html
- seylii/templates/peachjam/_header.html
> Add SeyLII collections menu and update blurb

- africanlii/templates/africanlii/au_detail_page.html
- africanlii/templates/peachjam/home.html
also make sm columns lg, since they have a lot of text
> bring courts back to africanlii homepage

- peachjam/resources.py
> Export case numbers

- ulii/templates/peachjam/_footer.html
> Ulii footer logo

- africanlii/templates/peachjam/home.html
- liiweb/static/stylesheets/components/_hero.scss
- liiweb/templates/liiweb/home.html
> Provide a background colour for hero search boxes to make them stand out

- peachjam/admin.py
- Genericdocument throws error when you save without date.
> Fix date field

- africanlii/static/stylesheets/africanlii.scss
- africanlii/templates/peachjam/home.html
- adds video to AGP homepage:
closes #1162
> Agp homepage video

- tanzlii/templates/peachjam/_header.html
> Tanzlii menu items

- eswatinilii/templates/peachjam/_header.html
> Add court rolls menu item

- africanlii/admin.py
- africanlii/resources.py
- adds ratification bulk import
closes #1212
> Ratification bulk import

- peachjam/templates/peachjam/_quick_search.html
- peachjam/templates/peachjam/author_detail.html
- peachjam/templates/peachjam/court_detail.html
- peachjam/templates/peachjam/document_nature_list.html
- adds quick search
closes #967
> Quick search

- peachjam/templates/peachjam/layouts/document_detail.html
- return the edit btn with updated permissions
Fixes #1286
> Edit button on document detail

- peachjam/js/utils/function.ts
- Fixes type error while generating TOC elements
fixes #1202
> Fixes type error while getting heading tags

- peachjam/templates/peachjam/layouts/document_detail.html
> Language dropdown

- peachjam/views/documents.py
Ref https://github.com/laws-africa/peachjam/issues/1302
> lesotholii is leslii for app configuration

- peachjam/js/peachjam.ts
this was stopping us from filtering out events we didn't care about
:facepalm:
> fix sentry bug

- eswatinilii/templates/peachjam/_header.html
> Add eSwatiniLII documents and guidelines menu item

- peachjam/resources.py
- instead of adding a new field, just remove it from excluded fields.
> Fix content_html in resource

- peachjam_search/documents.py
- peachjam_search/tasks.py
- Adds indexing when related models are saved.
closes #1243
> Related models indexing

- peachjam/admin.py
> Fix alternative names has changed

- peachjam/adapters/adapters.py
> Fix document nature code in adapter

- peachjam/templates/peachjam/_quick_search.html
- peachjam/templates/peachjam/author_detail.html
- peachjam/templates/peachjam/court_detail.html
- peachjam/templates/peachjam/document_nature_list.html
- peachjam/templates/peachjam/gazette_list.html
- peachjam/templates/peachjam/gazette_year.html
- peachjam/templates/peachjam/layouts/document_list.html
- peachjam/views/courts.py
- peachjam/views/gazette.py
- peachjam/views/judgment.py
- Adds text search for listing pages
- Adds text search for gazettes
closes #967 
https://www.loom.com/share/72e6e54142ca474daf17028b9b802ab3?sid=13a3a7e8-cea1-4d14-ba19-cf0cacc65f0e
> Text search

- peachjam/models/settings.py
- peachjam/templates/peachjam/layouts/main.html
- peachjam/templatetags/peachjam.py
- multiple google analytics tags
closes #1306
> Support for multiple Google analytics tags

- liiweb/citations.py
- liiweb/tests/test_mnc_matcher.py
Fixes #1270
Note local court codes:
> take localities into account for court MNCs

- peachjam/models/core_document_model.py
- peachjam/tests/test_citations.py
Otherwise the old extracted citations aren't touched again.
> clean old citations before extracting new ones

- liiweb/templates/peachjam/_footer.html
> Fix layout of social media links in footer

- peachjam/templates/peachjam/judgment_detail.html
- peachjam/templates/peachjam/layouts/document_detail.html
> Display headnote and holding in metadata

- africanlii/templates/peachjam/home.html
- africanlii/tests.py
- africanlii/tests/test_views.py
- africanlii/views/home.py
- peachjam/tests/test_views.py
- peachjam/views/home.py
> Align the courts listed on the AfricanLII homepage with those listed on judgments listing page

- nigerialii/templates/peachjam/_footer.html
- fixes https://lawsafrica.sentry.io/issues/4188842418/events/735fb73bed16413ea826f08701a89b27/
> Nigerialii footer

- africanlii/templates/peachjam/soft_law_list.html
- peachjam/templates/peachjam/author_detail.html
- peachjam/templates/peachjam/layouts/document_list.html
- peachjam/templates/peachjam/legal_instrument_list.html
- peachjam/templates/peachjam/taxonomy_detail.html
- Added the include in the base template and removed duplicates.
fixes #1372
> Fix doc count in generic document list

- open_by_laws/templates/peachjam/_header.html
> add OBL banner

- .github/workflows/deploy.yml
This sets up a generic lii at lii.laws.africa for documentation and training.
> deploy to generic lii

- africanlii/resources.py
- We need to add the attribute value to show the values in the preview :roll_eyes: 
closes #1381
> Preview dates for ratification bulk import

- peachjam/context_processors.py
- peachjam/js/components/DocumentContent/enrichments-manager.ts
- peachjam/js/components/DocumentContent/selection-search.ts
- peachjam/js/locale/en/translation.json
- peachjam/js/locale/fr/translation.json
- peachjam/js/locale/sw/translation.json
- peachjam/js/peachjam.ts
- peachjam/templates/peachjam/layouts/main.html
https://www.loom.com/share/2dc9bae1fbf44b3f985b36ba19ac44e6
* search for selection
* js config injection to simplify JS init
> search for selection in document v iew

- peachjam/templates/peachjam/judgment_detail.html
> Add flynote metadata to judgment detail view

- peachjam/models/judgment.py
- peachjam/views/courts.py
> Fix n+1error

- lawlibrary/templates/liiweb/locality_legislation_list.html
- lawlibrary/views/legislation.py
Fixes the breadcrumb link for the provincial and municipal legislation list views on LawLibrary.
> Fix breadcrumb link

- peachjam/settings.py
this makes it easier to see where db conns are coming from when viewing psql connections.
this will help us to understand our large number of connections
> add app name to database connection string

- peachjam/js/components/DocumentContent/ShareSelectionModal.vue
- peachjam/js/components/DocumentContent/enrichments-manager.ts
- peachjam/js/components/DocumentContent/selection-share.ts
- peachjam/js/components/FindDocuments/SearchResult.vue
https://www.loom.com/share/412dc1c6b3794d978e6fd6806e1240c7
Closes #1413
> selection sharing

- peachjam/tasks.py
- guard against no ingestor available when deleting
fixes #1457
> Fix ingestor delete method

- peachjam/context_processors.py
- peachjam/templates/peachjam/layouts/main.html
- adds language to google analytics
> Language in Google Analytics

- peachjam/models/core_document_model.py
> Mimetype check in source document

- liiweb/templates/liiweb/home.html
- seylii/settings.py
- seylii/static/stylesheets/seylii.scss
- seylii/templates/liiweb/home.html
- seylii/templates/seylii/donate.html
- seylii/urls.py
- seylii/views.py
> Seylii donate button and page

- peachjam/admin.py
> fixes help link

- peachjam/models/core_document_model.py
- check if source file pk is set
- check if pdf is available
> fixes doc mimetype check

- peachjam/admin.py
- peachjam/templates/admin/change_form.html
- peachjam/templates/admin/change_list.html
- check if context is available
- fix help link
fixes #1500
> Admin help topic context

- peachjam/admin.py
> Admin panel bug fix

- peachjam/views/courts.py
https://www.loom.com/share/58d9ad944e90441bb05f815418fc6c24?sid=340fecd9-6c05-41f8-bb04-c4cd67839e5c
> Guard for handling invalid months

- peachjam/adapters/adapters.py
- removes existing relationships before ingesting
fixes #1494
> Remove exising relationships in adapter

- peachjam/settings.py
https://github.com/pennersr/django-allauth/blob/main/ChangeLog.rst
> fixes allauth config

- peachjam/models/core_document_model.py
- peachjam/views/generic_views.py
fixes https://lawsafrica.sentry.io/issues/4207247471/
Before:
After:
> smarter relationship loading to avoid N+1

- africanlii/views/home.py
- africanlii/views/taxonomy.py
- liiweb/views/general.py
- peachjam/templates/peachjam/_taxonomy_list.html
- peachjam/views/taxonomy.py
taxonomy n+1 queries
___Before___
___After___
> Taxonomy n+1

- peachjam/adapters/adapters.py
- Get taxonomy topics from indigo adapter
- clear existing taxonomy topics
closes #1475
> Taxonomy topics from indigo adapter

- peachjam/templates/peachjam/layouts/document_detail.html
> Add copy button for Law Report Citations

- africanlii/views/au.py
___Before___
___After___
closes #1517
> N+1 in au/rec

- peachjam/js/components/FindDocuments/SearchResult.vue
- peachjam/js/components/FindDocuments/index.vue
https://www.loom.com/share/b39123496adc4e169acd83442ef925dd
> Fix search faceting bug

- peachjam/templates/peachjam/_article_list.html
- peachjam/templates/peachjam/_recent_article_list.html
- peachjam/templates/peachjam/article_detail.html
> Images and social media in article

- peachjam/admin.py
- peachjam/resources.py
https://www.loom.com/share/2ed7708a87664d63a815f3e1df5796ac?sid=1296b3db-64c9-4255-93e7-2501636e4f8b
> Bulk import attorneys

- africanlii/views/taxonomy.py
> fix for africanlii taxonomy listing page

- peachjam/js/components/FindDocuments/FacetBadges.vue
- peachjam/js/components/FindDocuments/index.vue
- peachjam/js/locale/en/translation.json
- peachjam/js/locale/fr/translation.json
- peachjam/js/locale/pt/translation.json
- peachjam/js/locale/sw/translation.json
- peachjam_search/views.py
https://www.loom.com/share/41b23a15915446beafd6a8c42920b94f?sid=bb185d5d-bae9-4268-94a4-cbe6ce2066c3
closes #1462
> Search tweaks

- peachjam/admin.py
> Show attached files tab in generic documents admin

- africanlii/templates/africanlii/au_detail_page.html
- africanlii/views/taxonomy.py
- liiweb/templates/liiweb/pocketlaw.html
- peachjam/templates/peachjam/taxonomy_first_level_detail.html
> Updated links to user guide

- peachjam/views/legislation.py
> Update notice for uncommenced legislation

- peachjam/js/components/DocumentContent/index.ts
- adds a table of content element to show books in full
https://www.loom.com/share/40e18fa86fd742b487e378909a3680d8?sid=c199ecab-2b25-47ce-85a8-64328a5d7809
closes #1545
> Show full text in book

- peachjam/views/legislation.py
> Disclaimer in metadata

- peachjam/settings.py
> Configure CONN_MAX_AGE

- peachjam/views/legislation.py
> Show warning for legislation that has a future commencement date

- peachjam/views/legislation.py
- guards against None in future commenements
> Fix future commencements notice

- peachjam/views/legislation.py
> Checks for null commencement date

- peachjam/admin.py
- peachjam/templates/peachjam/_timeline_events.html
- peachjam/views/legislation.py
This page (https://namiblii.org/akn/na/act/2021/3/eng@2021-10-01) will also have a commencements table as part of the coverpage under Document details.
> Partial commencements

- .github/workflows/deploy.yml
> Fix rwandalii deploy name

- rwandalii/templates/peachjam/terms_of_use.html
- organisation in terms of use
> Rwandalii terms of use

- peachjam/helpers.py
- peachjam/templates/peachjam/document_popup.html
- peachjam/views/widgets.py
Look up portions in HTML if possible.
> provision popups

- peachjam/adapters/adapters.py
To test locally:
1) Make sure you have "African Regional Bodies" setup as a country.
2) Make sure you have "African Union" setup as a locality.
3) Setup an ingestor with the following `token`, `api_url`, `places` and `actor` ingestor settings.
4) Run `./manage.py process_tasks`.
> Filter ingested documents by actor

- peachjam/graph/ranker.py
Fixes https://lawsafrica.sentry.io/issues/4700076180/
> guard against no ranks when calculating pivot

- peachjam_api/public_views.py
- peachjam_api/serializers.py
> add case numbers and judges to judgment api metadata

- peachjam/forms.py
Resolves https://github.com/laws-africa/peachjam/issues/1643
> Handle NoneType error in case admin emails are not set

- lawlibrary/templates/liiweb/donate.html
- seylii/templates/liiweb/donate.html
- Updates SeyLII's and LawLibrary donation page templates
> SeyLII donation page

- peachjam/static/js/judgment_duplicates.js
sometimes they start with spaces
> trim cookies

- eswatinilii/templates/liiweb/home.html
> Remove logos

- peachjam/models/relationships.py
- peachjam/views/generic_views.py
> Don't show relationships for deleted documents

- eswatinilii/templates/liiweb/home.html
- ghalii/templates/liiweb/home.html
- lawlibrary/templates/lawlibrary/home.html
- lesotholii/templates/liiweb/home.html
- liiweb/templates/liiweb/home.html
- malawilii/templates/liiweb/home.html
- namiblii/templates/liiweb/home.html
- peachjam/templates/peachjam/_social_media.html
- seylii/templates/liiweb/home.html
- sierralii/templates/liiweb/home.html
- tanzlii/templates/liiweb/home.html
- tcilii/templates/liiweb/home.html
- ulii/templates/liiweb/home.html
- zambialii/templates/liiweb/home.html
- zanzibarlii/templates/liiweb/home.html
- zimlii/templates/liiweb/home.html
> Remove the banner images and re-consider how to add graphical elements to the homepage

- liiweb/templates/liiweb/home.html
> Add a link to Help under search on Main Page

- peachjam/adapters/adapters.py
Tested manually with a refresh on my local ingestor.
> don't fetch bills from indigo

- peachjam/js/components/FindDocuments/SearchPagination.vue
- peachjam/templates/peachjam/_pagination.html
> As a search user I want to go beyond page 8 of paginated search results

- africanlii/templates/africanlii/au_detail_page.html
- africanlii/templates/peachjam/home.html
- lawlibrary/templates/lawlibrary/home.html
- liiweb/templates/liiweb/home.html
- peachjam/static/stylesheets/_global.scss
- peachjam/templates/peachjam/_court_list.html
- peachjam/templates/peachjam/judgment_list.html
Loom https://www.loom.com/share/64a491cc03f741db89e3d4751b32f132?sid=4c6cb653-6737-4706-894d-e4e69a50354e
> removed the heading-underlined class

- africanlii/templates/peachjam/layouts/main.html
- lawlibrary/templates/peachjam/layouts/main.html
- Removes plausible analytics for lawlibrary
- Adds matomo analytics for africanlii
> Matomo analytics

- peachjam_search/views.py
Fixes https://github.com/laws-africa/peachjam/issues/1713
https://www.loom.com/share/a3c1b6d654c14820b60915a6397dfa4e
> ensure API and Vue concept of search page size aligns

- liiweb/templates/peachjam/_footer.html
> ZanzibarLII url

- africanlii/templates/peachjam/_footer.html
> Update footer on AfricanLII

- peachjam/js/components/FindDocuments/JsonTable.vue
- peachjam/js/components/FindDocuments/SearchResult.vue
- peachjam/js/components/FindDocuments/index.vue
> show score as table so it's easier to debug

- peachjam/graph/ranker.py
the geometric mean is too small; only at higher values do we get reasonable score influence
see https://colab.research.google.com/drive/1KlYC7A9JeqS_uaLhL8yv_IrAmHHXNCdK
> use p99 as pagerank pivot

- peachjam/adapters/adapters.py
- tweaks to adapter to support v2 api
> Adapter tweaks

- tanzlii/templates/peachjam/_header.html
- updates to tanzlii menu
closes #1735
> Tanzlii menu updates

- peachjam/resources.py
This adds download url to the exporter
> Download url in export resource

- peachjam/views/generic_views.py
- Fixes the get object method to handle 404 properly
closes #1753
> Fix get object method to throw 404 error

- peachjam/admin.py
> Add an author filter in the generic document admin

- gazettes/views.py
> KeyError: 'za-gt'

- peachjam/adapters/gazettes.py
> Fix adapter params

- peachjam/resolver.py
- this updates the resolver domains to include kenyalaw
closes laws-africa/kenyalaw-pj#21
> Update resolver domains include kenyalaw

- malawilii/templates/peachjam/_header.html
- zambialii/templates/peachjam/_header.html
> Add Bills to Zambialii and Malawilii header

- peachjam/admin.py
https://www.loom.com/share/0b036d988c814e2180c3e5544ead5be9
> fix creating new relationships

- peachjam/tasks.py
before this, the error was handled by background_task and never raised for sentry to handle.
instead, we now report it during background_task's signal handler
> correctly handle background task errors in sentry

- peachjam_search/views.py
fixes https://lawsafrica.sentry.io/issues/5388006767/
> handle badly-formatted previous search UUIDs

- peachjam/settings.py
- peachjam/views/document_problem.py
This fixes the document problem view missing template
closes https://github.com/laws-africa/peachjam/issues/1841
> Fix document problem view

- peachjam/context_processors.py
avoid AttributeError while fetching the language code
closes https://github.com/laws-africa/peachjam/issues/1844
> Fix language code attribute

- peachjam/templates/peachjam/judgment_list.html
- peachjam/views/judgment.py
- adds document count to judgments page
closes https://github.com/laws-africa/kenyalaw-pj/issues/108
> Add doc count to judgments

- peachjam/views/courts.py
- add attorney and outcomes to prefetch
> Prefetch attorneys and outcomes

- peachjam/views/courts.py
This allows us to exclude certain facets on judgment listing page.
We need this to control the facets on kenyalaw
> Exclude certain facets in judgment listing

- peachjam/tests/test_citations.py
- pyproject.toml
> Citation test fix

- peachjam/js/components/FindDocuments/index.vue
- peachjam/js/components/ListFacets.vue
- peachjam/models/judgment.py
- peachjam/views/courts.py
- peachjam_search/views.py
- this allows judges to be configurable in the list and search filters
> Make judges label configurable in filters

- package-lock.json
- package.json
fixes some js bugs and adds .akn--no-border for tables
> latest law widgets

- peachjam_search/documents.py
> limit max length of text sent to elasticsearch

- peachjam/forms.py
> clean upload file name for new document uploads

- peachjam/templates/peachjam/layouts/document_detail.html
closes https://github.com/laws-africa/peachjam/issues/1872
> X logo for detail pages

- liiweb/views/legislation.py
- peachjam/views/legislation.py
> fix doc_type for quick search

- lawlibrary/templates/liiweb/legislation_list.html
- lawlibrary/templates/liiweb/locality_legislation_list.html
- liiweb/templates/liiweb/legislation_list.html
- liiweb/templates/liiweb/locality_legislation_list.html
- liiweb/views/legislation.py
- peachjam/templates/peachjam/layouts/document_list.html
> Locality legislation fixes

- peachjam/views/courts.py
> sort judgments by -date

- .github/workflows/build.yml
- .gitignore
- package-lock.json
- package.json
- webpack.config.js
This uploads sourcemaps to sentry during the build phase.
as per https://docs.sentry.io/platforms/javascript/sourcemaps/uploading/webpack/
> emit source maps for sentry

- peachjam/templates/peachjam/layouts/main.html
update the sentry js sdk to 8.5.1
> Update sentry javascript sdk

- peachjam/forms.py
- peachjam/settings.py
- peachjam/templates/account/login.html
- peachjam/templates/account/password_reset.html
- peachjam/templates/account/password_reset_from_key.html
- peachjam/templates/account/signup.html
- peachjam/templates/allauth/layouts/base.html
- peachjam/templates/peachjam/_document_detail_toolbar.html
- peachjam/templates/peachjam/_messages.html
- peachjam/templates/peachjam/layouts/base.html
- peachjam/templates/peachjam/layouts/main.html
- peachjam/views/documents.py
- peachjam/views/folder.py
- peachjam/views/generic_views.py
updates to auth pages layouts 
check for authenticated user before saving documents
closes https://github.com/laws-africa/peachjam/issues/1885
> Auth updates

- .pre-commit-config.yaml
- gazettes/urls.py
* fix for precommit and .map files
* fix gazettes urls
> don't change EOL for js map files

- Dockerfile
this is part of our python/django version update. the latest version is 22.0.0 - 2024-04-17, but I'd rather not be cutting edge since it shows a number of breaking changes.
see https://docs.gunicorn.org/en/latest/news.html for details
> recent (almost latest) gunicorn from 2023-07-19

- peachjam/views/courts.py
- peachjam/views/judgment.py
ref https://lawsafrica.sentry.io/issues/5656774100/ and others
> reduce n+1 queries

- africanlii/admin.py
- africanlii/forms.py
- africanlii/templates/africanlii/au_institution_detail.html
- africanlii/templates/africanlii/member_state_detail.html
- peachjam/templates/peachjam/layouts/document_list.html
* fix member state document listing
* fix organ document listing
> Ratifications fixes

- africanlii/locale/en/LC_MESSAGES/django.po
- africanlii/locale/fr/LC_MESSAGES/django.po
- africanlii/locale/pt/LC_MESSAGES/django.po
- africanlii/locale/sw/LC_MESSAGES/django.po
- liiweb/locale/en/LC_MESSAGES/django.po
- liiweb/locale/fr/LC_MESSAGES/django.po
- liiweb/locale/pt/LC_MESSAGES/django.po
- liiweb/locale/sw/LC_MESSAGES/django.po
- peachjam/js/components/FindDocuments/AdvancedSearchFields.vue
- peachjam/locale/en/LC_MESSAGES/django.po
- peachjam/locale/fr/LC_MESSAGES/django.po
- peachjam/locale/pt/LC_MESSAGES/django.po
- peachjam/locale/sw/LC_MESSAGES/django.po
- peachjam_search/documents.py
- peachjam_search/migrations/0005_es_mapping_add_judges_text.py
- peachjam_search/views.py
- tanzlii/locale/en/LC_MESSAGES/django.po
- tanzlii/locale/fr/LC_MESSAGES/django.po
- tanzlii/locale/pt/LC_MESSAGES/django.po
- tanzlii/locale/sw/LC_MESSAGES/django.po
- zanzibarlii/locale/fr/LC_MESSAGES/django.po
- zanzibarlii/locale/pt/LC_MESSAGES/django.po
- zanzibarlii/locale/sw/LC_MESSAGES/django.po
this requires re-indexing all judgments
> Judges text search

- peachjam/admin.py
https://www.loom.com/share/a25fd4e5be0247cd8d1b9ac7eaae07f5?sid=820a5d07-520d-4730-bac0-a75fae749b4d
closes https://github.com/laws-africa/kenyalaw-pj/issues/194
closes https://github.com/laws-africa/kenyalaw-pj/issues/195
> Gazettes admin

- malawilii/templates/liiweb/home.html
- zambialii/templates/liiweb/home.html
closes https://github.com/laws-africa/peachjam/issues/1970
> Survey banner

- peachjam/templates/peachjam/journal_list.html
- peachjam/views/books.py
- tanzlii/templates/peachjam/_header.html
closes https://github.com/laws-africa/peachjam/issues/1940
> Update Tanzlii nav menu

- pyproject.toml
This may help solve our intermittent database connection issues
See
https://forum.djangoproject.com/t/interfaceerror-and-transactionmanagementerror-postgresql/16924/11 and https://github.com/evansd/whitenoise/issues/556
> pin whitenoise 5.3.0

- africanlii/templates/africanlii/au_detail_page.html
- africanlii/views/au.py
closes https://github.com/laws-africa/peachjam/issues/1953
> Add regional courts to AU page

- peachjam/static/stylesheets/components/_entity-profile.scss
> vertically center short entity profile text

- peachjam/templates/peachjam/gazette_list.html
- peachjam/views/gazette.py
- breadcrumbs were not visible on the listing page because of the place check
- title case special issue
> Gazette tweaks

- peachjam/templates/peachjam/_header.html
- Hides login link if saved documents is not allowed
- Hides saved documents link
closes https://github.com/laws-africa/peachjam/issues/2010
> Saved documents fixes

- peachjam/templates/peachjam/robots.txt
https://developers.facebook.com/docs/sharing/webmasters/web-crawlers#identify-4
> disallow meta's AI bot

- peachjam/static/stylesheets/components/_document-content.scss
- peachjam/templates/peachjam/judgment_detail.html
- peachjam/templates/peachjam/layouts/document_detail.html
closes https://github.com/laws-africa/peachjam/issues/2018
> Changes order on judgment metadata

- peachjam/js/components/taxonomy-tree.ts
> tolerate TOC tree with no items

- peachjam/tests/test_views.py
- peachjam/views/generic_views.py
fixes https://github.com/laws-africa/peachjam/issues/1990
> validate year for year mixins

- peachjam/js/components/FindDocuments/SearchResult.vue
- peachjam/js/components/FindDocuments/index.vue
- peachjam_search/views.py
> Show alternative names in search results

- peachjam/js/components/FindDocuments/SearchResult.vue
- peachjam/js/components/FindDocuments/index.vue
Closes #1964 
After discussion with Thirusha, we thought a consistent gold colour was better than the primary colour.
> highligh best search result if it's score is better than the 2nd result

- ulii/templates/peachjam/_header.html
closes https://github.com/laws-africa/peachjam/issues/1786
> Add Hansard link to ulii header

- peachjam/adapters/indigo.py
resolves https://lawsafrica.sentry.io/issues/5911719477
> fix create publication file 

- peachjam/js/components/FindDocuments/AdvancedSearch.vue
- peachjam/js/components/FindDocuments/index.vue
> show filters button in advanced search

- africanlii/templates/peachjam/_header.html
- africanlii/templates/peachjam/taxonomy_list.html
- peachjam/templates/peachjam/taxonomy_list.html
fixes https://github.com/laws-africa/peachjam/issues/1933
> Change taxonomies and topics to collections on Africanlii

- africanlii/views/taxonomy.py
fixes https://github.com/laws-africa/peachjam/issues/2076
> fix date value for index listing page

- peachjam/adapters/indigo.py
should resolve https://lawsafrica.sentry.io/issues/5974346077
> don't save publication file when deleting a file on it

- peachjam/templates/peachjam/_quick_search.html
- peachjam/views/courts.py
- peachjam/views/gazette.py
- peachjam/views/judgment.py
- peachjam/views/legislation.py
the search UI no longer uses doc_type
> quick search must use nature not doc_type

- peachjam/admin.py
- peachjam/js/components/TaxonomyTopics.vue
- peachjam/js/components/index.ts
- peachjam/templates/admin/taxonomy_topic_tree.html
This adds taxonomy checkboxes instead of the dropdowns
https://www.loom.com/share/8c99f88677fa42799b90144fc8544579?sid=c6c755cf-bdfb-49ec-9dbf-4fd34d139242
closes https://github.com/laws-africa/peachjam/issues/2072
> Taxonomy checkboxes

- peachjam/admin.py
editors don't have visibility into work details
> move serial number back to key details

- peachjam/models/core_document_model.py
- peachjam/models/judgment.py
- peachjam/settings.py
- peachjam/templates/peachjam/causelist_list.html
- peachjam/views/causelist.py
closes https://github.com/laws-africa/kenyalaw-pj/issues/260
> Show only courts that have causelists

- peachjam/adapters/indigo.py
otherwise it thinks docs should be deleted that, well, shouldn't be
> ensure that check_for_deleted excludes docs

- peachjam/models/taxonomies.py
- peachjam/templates/peachjam/_taxonomies.html
- peachjam/templates/peachjam/_taxonomies_tree.html
- peachjam/templatetags/peachjam.py
- peachjam/views/generic_views.py
> Taxonomies as trees

- peachjam/admin.py
This filters for article tags in the admin.
> Filter for article tags in admin

- liiweb/views/legislation.py
- peachjam/forms.py
- peachjam/templates/peachjam/_child_documents.html
- peachjam/views/legislation.py
This has small changes to the legislation listing and detail views
closes https://github.com/laws-africa/peachjam/issues/2093
closes https://github.com/laws-africa/peachjam/issues/2088
closes https://github.com/laws-africa/peachjam/issues/2090
> Legislation listing changes

- tanzlii/templates/peachjam/_footer.html
> OAG updates

- peachjam/templates/peachjam/_document_table_row.html
- peachjam/views/generic_views.py
This is for https://github.com/laws-africa/kenyalaw-pj/issues/198
https://github.com/user-attachments/assets/46348ef7-616a-4662-80a7-b3d7820cbeb8
> added IDs to group titles

- peachjam/views/generic_views.py
https://lawsafrica.sentry.io/issues/6089366262/events/718609abb1da4f3bbc23e4ea2da4029d/
> fixes year group bug

- peachjam/static/stylesheets/components/_year_nav.scss
- peachjam/templates/peachjam/_court_years_list.html
- peachjam/templates/peachjam/_years_list.html
> ensure years line up better

- africanlii/templates/peachjam/home.html
> Changes to the AfricanLII homepage

- peachjam/templates/peachjam/_document_detail_toolbar.html
> Check staff permissions

- gazettes/static/css/_core.scss
- peachjam/static/stylesheets/components/_year_nav.scss
- peachjam/templates/peachjam/_court_months_list.html
> month navs

- peachjam/views/documents.py
fixes https://lawsafrica.sentry.io/issues/6017845374/
> handle bad citation value correctly

- peachjam/admin.py
- peachjam/models/judgment.py
- peachjam/views/courts.py
Closes [#301](https://github.com/laws-africa/kenyalaw-pj/issues/301)
> Ability to add profiles for Court Classes

- civlii/templates/liiweb/home.html
- eswatinilii/templates/liiweb/home.html
- ghalii/templates/liiweb/home.html
- lawlibrary/templates/liiweb/home.html
- lesotholii/templates/liiweb/home.html
- liiweb/templates/liiweb/home.html
- malawilii/templates/liiweb/home.html
- mauritiuslii/templates/liiweb/home.html
- namiblii/templates/liiweb/home.html
- nigerialii/templates/liiweb/home.html
- rwandalii/templates/liiweb/home.html
- seylii/templates/liiweb/home.html
- sierralii/templates/liiweb/home.html
- tanzlii/templates/liiweb/home.html
- tcilii/templates/liiweb/home.html
- ulii/templates/liiweb/home.html
- zambialii/templates/liiweb/home.html
- zanzibarlii/templates/liiweb/home.html
- zimlii/templates/liiweb/home.html
> updated home template to use the same structure

- peachjam/templates/peachjam/restricted_document_detail.html
- peachjam/views/documents.py
> Restricted document 403 view

- peachjam/models/judgment.py
- peachjam/templates/peachjam/_case_histories.html
- peachjam/tests/test_views.py
- peachjam/views/judgment.py
* case histories are shown in both directions
https://www.loom.com/share/7c482f3706cb43898b2fc8025828b7e7
> adjustments to case history

- peachjam/admin.py
this adds some missing translations for the admin
> Admin translate

- peachjam/templates/socialaccount/connections.html
> fix translation for social account template

- peachjam/templatetags/peachjam.py
This adds a isodate string template filter to parse iso date strings in templates
> iso datestring filter

- africanlii/templates/peachjam/home.html
africanlii doesn't inherit from liiweb so it missed this
> enable typeahead on africanlii homepage

- peachjam/adapters/indigo.py
- peachjam/tests/test_adapters.py
This means multiple ingestors from the same source can be responsible for different subsets of data.
> indigo ingestors check if they're responsible for an expression FRBR URI

- peachjam/adapters/indigo.py
Fixes https://lawsafrica.sentry.io/issues/6272227448/
> on GenericDocument, author is many-to-many

- peachjam/templates/peachjam/_case_histories.html
closes https://github.com/laws-africa/peachjam/issues/2268
> Fix case history tab

- peachjam/views/bills.py
fixes https://github.com/laws-africa/peachjam/issues/2286
> check for nature in context before removing for bills

- lawlibrary/views/legislation.py
- liiweb/views/legislation.py
> remove dates from the locality legislation listing views

- zanzibarlii/templates/peachjam/_header.html
closes https://github.com/laws-africa/peachjam/issues/2291
> Zanzibarlii gazettes menu item

- peachjam_search/engine.py
- peachjam_search/forms.py
fixes bad saved search results
> support created_at__gte for search

- peachjam/views/generic_views.py
This adds the citation treatments back. We fetch the treatments at the last minute as discussed.
It adds about 4 additional queries, this should scale better.
> Citation treatments

- peachjam_search/documents.py
fixes https://github.com/laws-africa/peachjam/issues/2249
> correctly filter generic documents on author.

- peachjam/adapters/indigo.py
fixes https://github.com/laws-africa/peachjam/issues/2287
> correctly set principal flag on non Legislation

- ghalii/templates/peachjam/_header.html
- peachjam/adapters/judgments.py
- tanzlii/templates/peachjam/_header.html
This adds AU menu items
Includes tweaks for the Judgment Adapter
> au menu items and adapter tweak

- ghalii/templates/peachjam/_header.html
- tanzlii/templates/peachjam/_header.html
> fix au headers

- CHECKS
- app.json
> move CHECKS to app.json

- peachjam/templates/peachjam/_document_content.html
- peachjam/templates/peachjam/_document_content_sidebar.html
- peachjam/templates/peachjam/_header.html
- peachjam/templates/peachjam/_quick_search.html
- peachjam/templates/peachjam/_social_media.html
closes https://github.com/laws-africa/peachjam/issues/2317
> Fix minor a11y issues

- zambialii/templates/peachjam/_header.html
closes https://github.com/laws-africa/peachjam/issues/2342
> Collections link for Zambialii

- app.json
zanzibar defaults to kiswahili, so we can simply check for "login" which is an id attribute
> zanzibar login check

- peachjam/admin.py
- peachjam/settings.py
- peachjam_search/documents.py
- peachjam_search/embeddings.py
- peachjam_search/engine.py
- peachjam_search/serializers.py
- peachjam_search/tests/test_embeddings.py
- peachjam_search/tests/test_engine.py
* KNN is declared in the ES 8 client.
* move JSON fields into Advanced tab in Admin and make readonly
> Legislation provision semantic search

- peachjam/static/stylesheets/_global.scss
- peachjam/templates/account/google_login_button.html
- peachjam/templates/account/login.html
- peachjam/templates/account/signup.html
- peachjam/templates/peachjam/_document_content_sidebar.html
- peachjam/templates/peachjam/_header.html
Adds the google login button to the signup page.
Adds the skip link class, to the skip documents content section
> Google login button

- peachjam/js/components/FindDocuments/index.vue
- peachjam/resources.py
- peachjam_search/views.py
We can build on this to download saved document folders (see #1770)
> Basic support for downloading search results (admin only)

- lawlibrary/templates/liiweb/locality_legislation_list.html
- liiweb/templates/liiweb/locality_legislation_list.html
closes https://github.com/laws-africa/peachjam/issues/2373
> Locality legislation follow button 

- peachjam/templates/peachjam/emails/user_following_alert_email.html
so that we can track engagement
> following alert utm parameters

- peachjam/middleware.py
- peachjam/templates/peachjam/_user_menu.html
- peachjam/templates/user_account/home.html
- peachjam/urls.py
* ensure /follow/ is not cached
* move document-access-groups under accounts (also prevents caching)
* add Following to cards in My account
> add following, fix caching

- peachjam/views/taxonomy.py
this is so the 403.html template is used
> raise permission denied

- peachjam/js/components/DocDiffs/ProvisionChangedGutterItem.vue
- peachjam/js/components/DocDiffs/index.ts
- peachjam/js/components/DocumentContent/ShareSelectionModal.vue
- peachjam/js/components/analytics.ts
- peachjam/js/peachjam.ts
- peachjam/templates/peachjam/layouts/document_detail.html
- peachjam/templates/peachjam/layouts/main.html
See also https://docs.google.com/spreadsheets/d/1TO0B92dBuheOi_RmenL3Tkh7kSo9G2RyLRcjG8Fn2So/edit?pli=1&gid=0#gid=0
> Attribute-driven event tracking for in-page feature usage

- peachjam/forms.py
AWS and other email senders don't allow us to spoof the "from", but reply-to is allowed
> change email sending so we can set reply-to

- peachjam/signals.py
fixes https://github.com/laws-africa/peachjam/issues/2432
> customer io typo

- peachjam/models/core_document.py
> fix for when no notice is present

- lawlibrary/settings.py
- peachjam/emails.py
- peachjam/models/user_following.py
- peachjam/settings.py
- peachjam/templates/peachjam/emails/user_following_alert.email
- peachjam/tests/test_emails.py
- peachjam_search/models.py
- peachjam_search/templates/peachjam/emails/search_alert.email
- peachjam_search/templates/peachjam_search/_saved_search_filters.html
- peachjam_search/templates/peachjam_search/_saved_search_modal.html
- peachjam_search/templates/peachjam_search/saved_search_list.html
- pyproject.toml
- tanzlii/settings.py
* new email backend for sending email alerts via customerio
* this requires us to serialise context to send via the API
* corresponding minor changes to email templates
> customerio transactional email backend for alert emails

- peachjam/js/peachjam.ts
these were set previously accidentally
> clear customerio cookies

- liiweb/templates/liiweb/_hero_search.html
- peachjam/admin.py
- zambialii/templates/peachjam/_header.html
closes https://github.com/laws-africa/peachjam/issues/2438
closes https://github.com/laws-africa/peachjam/issues/2400
closes https://github.com/laws-africa/peachjam/issues/2452
> Zambialii header, admin improvements and help link

- peachjam/auth.py
- peachjam/customerio.py
- peachjam/signals.py
this allows us to see how many are successful / how painful this is.
> track password reset events

- peachjam/js/components/Annotations/Annotation.vue
- peachjam/templates/peachjam/_annotation_detail.html
> As a user I want links in document comments to work

- tanzlii/templates/peachjam/_header.html
- ulii/templates/peachjam/_header.html
closes https://github.com/laws-africa/peachjam/issues/1115
> Menu items for EACA and EACJ

- peachjam_ml/signals.py
minor change to how the peachjam_ml signals are attached
> adjust signal

- tanzlii/settings.py
this turns on the peachjam subscription module for tanzlii
> Peachjam subs to Tanzlii

- peachjam/js/components/saved-documents.ts
- peachjam/templates/peachjam/layouts/document_detail.html
- peachjam/templates/peachjam/saved_document/_create.html
- peachjam/templates/peachjam/saved_document/_update.html
- peachjam/templates/peachjam/saved_document/_update_modal.html
> Show saved document details in the document detail page

- peachjam/analysis/citations.py
- peachjam/models/annotation.py
- peachjam/models/core_document.py
- peachjam/models/enrichments.py
- peachjam/templates/peachjam/_annotation_detail.html
- peachjam/templates/peachjam/provision_enrichment/_detail.html
- peachjam/tests/test_documents.py
- peachjam/views/compare.py
- peachjam/views/generic_views.py
- peachjam/xmlutils.py
- peachjam_search/documents.py
> Friendly provision titles

- tanzlii/templates/peachjam/_header.html
closes https://github.com/laws-africa/peachjam/issues/2504
> Tanzlii collections header

- peachjam/adapters/judgments.py
- peachjam_api/serializers.py
Fixes https://github.com/laws-africa/peachjam/issues/2447
We can filter by slugs.
> Fix taxonomy filter in adapter and serializer

- peachjam_api/public_views.py
for https://github.com/laws-africa/peachjam/issues/2496
will close issue after updating the ingestor with the language code and delete extra documents
> add language filter to document api

- peachjam/admin.py
can't save DocumentContent if Document doesn't have a pk
> avoid bug when uploading new document

- peachjam/templates/peachjam/_document_table_row.html
- peachjam/templates/peachjam/_document_taxonomies.html
> don't hide blurb and summary in listing views on mobile

- tanzlii/templates/peachjam/_header.html
- ulii/templates/peachjam/_header.html
> au menu items for ulii

- peachjam/adapters/indigo.py
- peachjam/views/legislation.py
Fixes https://lawsafrica.sentry.io/issues/6717369385 https://lawsafrica.sentry.io/issues/6717625582 
Is there a neater way of doing it, like a setting on the ProvisionEnrichment class? (we can implement the next time we add a subclass)
> Fix update provision enrichments

- peachjam/templates/peachjam/judgment_detail.html
> Move flynote into the summary block on detail page

- peachjam/templates/peachjam/provision_enrichment/_document_uncommenced_provision_list.html
- peachjam/templates/peachjam/provision_enrichment/_uncommenced_provision_detail.html
- peachjam/templates/peachjam/provision_enrichment/_uncommenced_table.html
- peachjam/templates/peachjam/provision_enrichment/uncommenced_provision_detail.html
- peachjam/urls/root.py
- peachjam/views/legislation.py
not sure if there's a better way to cut down on db calls in the view? very open to suggestions
https://www.loom.com/share/e2c383f3a4634686871dc1236f174dab
> Improve provision enrichments list

- liiweb/templates/peachjam/provision_enrichment/uncommenced_provision_list.html
- peachjam/templates/peachjam/provision_enrichment/uncommenced_provision_list.html
> liiweb to extend uncommenced_provision_list.html

- .github/workflows/test.yml
- peachjam/adapters/__init__.py
- peachjam/adapters/gitbook.py
- peachjam/static/stylesheets/components/_document-content.scss
- peachjam/tests/test_gitbook.py
- pyproject.toml
* new ingestor that fetches content (in gitbook markdown format) from a github repo
* the ingestor parses the different .md files into one big html file and builds up a table of contents
Ingestors are now documented: https://liieditors.docs.laws.africa/site-admin/ingestors
> Gitbook adapter

- peachjam/js/components/ProvisionCitations/ProvisionCitationCount.vue
- peachjam/templates/peachjam/provision_enrichment/provision_citations.html
- peachjam/views/generic_views.py
- peachjam/views/legislation.py
- adds breadcrumbs
- changes title wording
- changes gutter item count to show citing document count
- change quotation icon
> Provision citations tweaks

- peachjam/models/user_following.py
> Fix search email

- manage.py
- peachjam/settings.py
- peachjam/templates/peachjam/document/_access_restricted.html
- peachjam/templates/peachjam/provision_enrichment/provision_citations.html
- peachjam/views/legislation.py
- peachjam_subs/models.py
- peachjam_subs/test_app/settings.py
- tanzlii/settings.py
closes https://github.com/laws-africa/peachjam/issues/2653
> Permissions for incoming provision citations

- africanlii/templates/peachjam/_header.html
- africanlii/views/agp.py
> mooc header menu item

- africanlii/tests/test_views.py
- peachjam/js/api.ts
- peachjam/js/peachjam.ts
- peachjam/templates/peachjam/_set_language.html
- peachjam/templates/peachjam/layouts/base.html
- peachjam/templatetags/peachjam.py
* fix following in non-English pages (otherwise the parameters are translated)
* correct top-level page language code
* make CSRF for language chooser dynamic (otherwise a cookie is set on all pages, breaking caching)
> fix following in non-English pages, language stuff

- peachjam/js/components/document-detail.ts
- peachjam/js/components/index.ts
- peachjam/templates/peachjam/layouts/document_detail.html
otherwise we hit /debug for every document
> load document debug only if perms allow it

- peachjam/js/components/Annotations/Annotation.vue
- peachjam/js/components/Annotations/AnnotationList.vue
- peachjam/js/components/Annotations/index.ts
- peachjam/js/components/DocumentContent/citation-links.ts
- peachjam/js/components/DocumentContent/enrichments-manager.ts
- peachjam/js/components/DocumentContent/selection-search.ts
- peachjam/js/components/DocumentContent/selection-share.ts
- peachjam/js/components/DocumentContent/selection-toolbar.ts
- peachjam/js/components/RelationshipEnrichment/RelationshipEnrichment.vue
- peachjam/js/components/RelationshipEnrichment/index.ts
- peachjam/js/locale/en/translation.json
- peachjam/js/locale/fr/translation.json
- peachjam/js/locale/pt/translation.json
- peachjam/js/locale/sw/translation.json
- peachjam/static/stylesheets/components/_document-content.scss
- peachjam/static/stylesheets/components/_gutter.scss
This makes it much easier to use text-selection based actions in the document view, such as adding comments, searching and sharing.
* selection gutter menu uses icons and text, left-aligned, bigger icons
* selection gutter menu and active gutter card have drop shadows to stand out more
* selection popup menu on mobile, rather than gutter
* always show gutter on mobile to avoid jumping when text is selected and the gutter item is added
* reduce gutter padding on mobile
* activate comment textarea when adding a comment
> Better text selection context actions for mobile

- peachjam/js/components/DocumentContent/enrichments-manager.ts
> guard against null akn

- peachjam/templates/peachjam/_header.html
- peachjam/templates/peachjam/my/_frontpage.html
- peachjam/templates/peachjam/my/_frontpage_anon.html
- peachjam/templates/peachjam/my/_frontpage_loader.html
- peachjam/templates/peachjam/my/layout.html
- peachjam/templates/user_account/home.html
- peachjam_subs/templates/peachjam_subs/_subscription_card.html
> Small changes to My LII on the homepage

- peachjam/static/stylesheets/components/_terms-of-use.scss
- peachjam/templates/peachjam/_terms_of_use_content.html
adds numbering, moves styling into scss
> terms layout, extensibility
